import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import existing curated reactions from current massiveReactionsData if available
const targetPathClient = path.resolve(__dirname, '../src/data/massiveReactionsData.js');
const targetPathServer = path.resolve(__dirname, '../../server/src/reactions/massiveReactionsData.js');

console.log('Generating 5,000+ Class 10-12 Chemical Reactions database...');

// Script content to be generated into massiveReactionsData.js
const code = `// Master Massive Reactions Database (>5,000 Reactions)
// Fully covers Class 10 to Class 12 NCERT, CBSE & JEE Chemistry:
// - Class 10: Chemical Reactions & Equations, Acids Bases Salts, Metals & Non-metals, Carbon & its Compounds
// - Class 11: Redox, Hydrogen, s-Block, p-Block, Hydrocarbons, GOC, Environmental
// - Class 12: Solid State, Solutions, Electrochemistry, Surface Chemistry, Isolation, p/d/f Block, Coordination, Haloalkanes, Alcohols/Phenols, Aldehydes/Ketones, Amines/Diazonium, Biomolecules, Polymers

export const REACTION_CATEGORIES = [
  'All',
  'Diazonium & Benzene',
  'Aldehydes & Ketones',
  'Haloalkanes & Haloarenes',
  'General Organic Chemistry (GOC)',
  'Metals & Non-metals',
  'Acids & Bases (Neutralization)',
  'Precipitation & Salt Matrix',
  'Qualitative Inorganic Analysis',
  'Industrial & Redox',
  'Esterification & Scents',
];

export const CURATED_MASTER_REACTIONS = [
  // --- Class 10 NCERT Milestone Reactions ---
  {
    id: 'rx_class10_mg_combustion',
    name: 'Combustion of Magnesium Ribbon in Oxygen',
    category: 'Metals & Non-metals',
    inputs: ['Mg', 'O2'],
    conditions: ['heat'],
    outputs: ['MgO'],
    products: ['MgO'],
    equation: '2Mg + O₂ ──► 2MgO',
    type: 'Combination & Exothermic Combustion',
    color: '#ffffff',
    observation: 'white_light',
    description: 'Burns with a dazzling white flame to form a white ash.',
    mechanism: 'Magnesium ribbon undergoes vigorous exothermic combustion in air, releasing high energy photons (blinding white-hot flame) and leaving powdery Magnesium Oxide ash residue.',
    jeeRelevance: 'Essential Class 10 NCERT Chapter 1 Experiment',
    xp: 200,
  },
  {
    id: 'rx_class10_mg_combustion_ambient',
    name: 'Magnesium Ignition in Air/Oxygen',
    category: 'Metals & Non-metals',
    inputs: ['Mg', 'O2'],
    conditions: [],
    outputs: ['MgO'],
    products: ['MgO'],
    equation: '2Mg + O₂ ──► 2MgO',
    type: 'Combination & Exothermic Combustion',
    color: '#ffffff',
    observation: 'white_light',
    description: 'Burns with a dazzling white flame to form a white ash.',
    mechanism: 'Magnesium vigorously oxidizes in oxygen releasing intense heat and brilliant white light.',
    jeeRelevance: 'Essential Class 10 NCERT Chapter 1 Experiment',
    xp: 200,
  },
  {
    id: 'rx_pb_no3_decomposition',
    name: 'Thermal Decomposition of Lead Nitrate',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['Pb(NO3)2'],
    conditions: ['heat'],
    outputs: ['PbO', 'NO2', 'O2'],
    products: ['PbO', 'NO2', 'O2'],
    equation: '2Pb(NO₃)₂ ──(heat)──► 2PbO + 4NO₂↑ + O₂↑',
    type: 'Thermal Decomposition',
    color: '#f59e0b',
    observation: 'brown_fumes',
    description: 'Lead nitrate crystals crackle on dry heating, releasing pungent reddish-brown NO2 gas fumes and leaving a yellow PbO residue.',
    jeeRelevance: 'Core Class 10 NCERT decomposition benchmark',
    xp: 180,
  },
  {
    id: 'rx_slaking_of_lime',
    name: 'Slaking of Quicklime (Calcium Oxide)',
    category: 'Acids & Bases (Neutralization)',
    inputs: ['CaO', 'H2O'],
    conditions: [],
    outputs: ['Ca(OH)2'],
    products: ['Ca(OH)2'],
    equation: 'CaO + H₂O ──► Ca(OH)₂ + Heat',
    type: 'Combination & Highly Exothermic',
    color: '#ffffff',
    observation: 'heat_evolution',
    description: 'Quicklime reacts vigorously with water with a hissing sound, boiling the water and producing slaked lime (calcium hydroxide).',
    jeeRelevance: 'Class 10 NCERT Chapter 1 core experiment',
    xp: 150,
  },
  {
    id: 'rx_limewater_milky',
    name: 'Testing CO2 with Limewater',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['Ca(OH)2', 'CO2'],
    conditions: [],
    outputs: ['CaCO3', 'H2O'],
    products: ['CaCO3', 'H2O'],
    equation: 'Ca(OH)₂ + CO₂ ──► CaCO₃↓ + H₂O',
    type: 'Precipitation & Neutralization',
    color: '#ffffff',
    observation: 'turns_limewater',
    description: 'Colorless limewater turns milky due to insoluble Calcium Carbonate precipitate formation.',
    jeeRelevance: 'Class 10 & 11 gas identification test',
    xp: 160,
  },
  {
    id: 'rx_limewater_excess_co2',
    name: 'Clearing of Milky Limewater with Excess CO2',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['CaCO3', 'CO2', 'H2O'],
    conditions: [],
    outputs: ['Ca(HCO3)2'],
    products: ['Ca(HCO3)2'],
    equation: 'CaCO₃ + CO₂ + H₂O ──► Ca(HCO₃)₂ (aq)',
    type: 'Soluble Bicarbonate Formation',
    color: '#bae6fd',
    observation: 'milky_turns_clear',
    description: 'Milkiness dissolves upon passing excess CO2 due to formation of soluble Calcium Bicarbonate.',
    jeeRelevance: 'Class 10 NCERT Chapter 2 key analytical distinction',
    xp: 170,
  },
  {
    id: 'rx_fe_cuso4_displacement',
    name: 'Displacement of Copper by Iron',
    category: 'Metals & Non-metals',
    inputs: ['Fe', 'CuSO4'],
    conditions: [],
    outputs: ['FeSO4', 'Cu'],
    products: ['FeSO4', 'Cu'],
    equation: 'Fe + CuSO₄ ──► FeSO₄ + Cu',
    type: 'Single Metal Displacement',
    color: '#10b981',
    observation: 'blue_to_green',
    description: 'Sky-blue copper sulphate solution fades to pale green ferrous sulphate while reddish-brown metallic copper coats the iron nail.',
    jeeRelevance: 'Class 10 reactivity series flagship experiment',
    xp: 160,
  },
  {
    id: 'rx_zn_h2so4_effervescence',
    name: 'Zinc Granules Reaction with Dilute Acid',
    category: 'Acids & Bases (Neutralization)',
    inputs: ['Zn', 'H2SO4'],
    conditions: [],
    outputs: ['ZnSO4', 'H2'],
    products: ['ZnSO4', 'H2'],
    equation: 'Zn + H₂SO₄ ──► ZnSO₄ + H₂↑',
    type: 'Metal Acid Displacement',
    color: '#e0f2fe',
    observation: 'squeaky_pop',
    description: 'Brisk effervescence of hydrogen gas that burns with a characteristic squeaky pop sound near a burning splint.',
    jeeRelevance: 'Standard laboratory preparation of Hydrogen gas',
    xp: 160,
  },
  {
    id: 'rx_electrolysis_water',
    name: 'Electrolytic Decomposition of Water',
    category: 'Industrial & Redox',
    inputs: ['H2O'],
    conditions: ['electricity'],
    outputs: ['H2', 'O2'],
    products: ['H2', 'O2'],
    equation: '2H₂O ──(electricity)──► 2H₂↑ + O₂↑',
    type: 'Electrolysis',
    color: '#38bdf8',
    observation: 'bubbling_electrodes',
    description: 'Decomposition into 2:1 volume ratio of Hydrogen gas at cathode and Oxygen gas at anode.',
    jeeRelevance: 'Class 10 NCERT Chapter 1 Electrolysis',
    xp: 190,
  },
  {
    id: 'rx_silver_chloride_sunlight',
    name: 'Photolytic Decomposition of Silver Chloride',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['AgCl'],
    conditions: ['sunlight'],
    outputs: ['Ag', 'Cl2'],
    products: ['Ag', 'Cl2'],
    equation: '2AgCl ──(sunlight)──► 2Ag + Cl₂↑',
    type: 'Photochemical Decomposition',
    color: '#64748b',
    observation: 'white_to_grey',
    description: 'White Silver Chloride turns grey in sunlight as metallic silver is liberated with evolution of pungent chlorine gas.',
    jeeRelevance: 'Black & white photography chemistry (Class 10)',
    xp: 170,
  },
  {
    id: 'rx_thermite',
    name: 'Thermite Welding Reaction',
    category: 'Industrial & Redox',
    inputs: ['Fe2O3', 'Al'],
    conditions: ['heat'],
    outputs: ['Al2O3', 'Fe'],
    products: ['Al2O3', 'Fe'],
    equation: 'Fe₂O₃ + 2Al ──(ignition)──► Al₂O₃ + 2Fe (molten) + Heat',
    type: 'Highly Exothermic Thermite Redox',
    color: '#f97316',
    observation: 'white_hot_molten_iron',
    description: 'Extremely exothermic reaction generating molten iron (>2500°C) used to weld railway tracks.',
    jeeRelevance: 'Class 10 Metallurgy & Class 12 Ellingham diagram',
    xp: 240,
  },
  {
    id: 'rx_esterification_ethyl_acetate',
    name: 'Fischer Esterification (Fruity Smell)',
    category: 'Esterification & Scents',
    inputs: ['CH3COOH', 'C2H5OH', 'H2SO4'],
    conditions: ['heat'],
    outputs: ['CH3COOC2H5', 'H2O'],
    products: ['CH3COOC2H5', 'H2O'],
    equation: 'CH₃COOH + C₂H₅OH ──(H₂SO₄/heat)──► CH₃COOC₂H₅ + H₂O',
    type: 'Acid-Catalyzed Esterification',
    color: '#fef08a',
    observation: 'fruity_smell',
    description: 'Pleasant sweet fruity fragrance of Ethyl Acetate ester develops upon gentle water-bath heating.',
    jeeRelevance: 'Class 10 & 12 carboxylic acid functional test',
    xp: 200,
  },
  {
    id: 'rx_saponification',
    name: 'Saponification (Soap Preparation)',
    category: 'Esterification & Scents',
    inputs: ['CH3COOC2H5', 'NaOH'],
    conditions: ['heat'],
    outputs: ['CH3COONa', 'C2H5OH'],
    products: ['CH3COONa', 'C2H5OH'],
    equation: 'CH₃COOC₂H₅ + NaOH ──(heat)──► CH₃COONa + C₂H₅OH',
    type: 'Alkaline Ester Hydrolysis',
    color: '#e2e8f0',
    observation: 'soapy_lather',
    description: 'Hydrolysis of ester with alkali produces sodium carboxylate salt (soap) and alcohol.',
    jeeRelevance: 'Class 10 Carbon Compounds & Class 12 Everyday Chemistry',
    xp: 190,
  },

  // --- Class 12 Organic Chemistry & Named Reactions ---
  {
    id: 'rx_diazotization',
    name: 'Diazotization of Aniline',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5NH2', 'NaNO2', 'HCl'],
    conditions: ['ice_cold', '0_5C'],
    outputs: ['C6H5N2Cl', 'NaCl', 'H2O'],
    products: ['C6H5N2Cl', 'NaCl', 'H2O'],
    equation: 'C₆H₅NH₂ + NaNO₂ + 2HCl ──(0-5°C)──► C₆H₅N₂⁺Cl⁻ + NaCl + 2H₂O',
    type: 'Diazotization',
    color: '#38bdf8',
    observation: 'clear_yellowish_solution',
    description: 'Aniline reacts with nitrous acid generated in situ at 0-5°C to yield stable Benzene Diazonium Chloride.',
    jeeRelevance: 'Very High (Crucial starting point for aromatic synthesis in JEE/NEET)',
    xp: 250,
  },
  {
    id: 'rx_sandmeyer_cl',
    name: 'Sandmeyer Reaction (Chlorobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuCl', 'HCl'],
    conditions: [],
    outputs: ['C6H5Cl', 'N2'],
    products: ['C6H5Cl', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuCl/HCl ──► C₆H₅Cl + N₂↑',
    type: 'Nucleophilic Aromatic Radical Substitution',
    color: '#0284c7',
    observation: 'bubbling',
    description: 'Decomposition of benzene diazonium chloride catalyzed by cuprous chloride yields chlorobenzene with rapid N2 evolution.',
    jeeRelevance: 'Top Tier (Standard Sandmeyer halide synthesis)',
    xp: 200,
  },
  {
    id: 'rx_sandmeyer_br',
    name: 'Sandmeyer Reaction (Bromobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuBr', 'HBr'],
    conditions: [],
    outputs: ['C6H5Br', 'N2'],
    products: ['C6H5Br', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuBr/HBr ──► C₆H₅Br + N₂↑',
    type: 'Nucleophilic Aromatic Radical Substitution',
    color: '#d97706',
    observation: 'bubbling_oily_layer',
    description: 'Cuprous bromide decomposes diazonium salt to produce pale yellow oily bromobenzene with N2 gas bubbling.',
    jeeRelevance: 'Standard Sandmeyer Bromide Synthesis',
    xp: 200,
  },
  {
    id: 'rx_sandmeyer_cn',
    name: 'Sandmeyer Cyanation (Benzonitrile)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuCN', 'KCN'],
    conditions: [],
    outputs: ['C6H5CN', 'N2'],
    products: ['C6H5CN', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuCN ──► C₆H₅CN + N₂↑',
    type: 'Sandmeyer Cyanation',
    color: '#475569',
    observation: 'bubbling',
    description: 'Introduction of cyano group onto benzene ring via cuprous cyanide yielding benzonitrile.',
    jeeRelevance: 'Gateway to benzoic acid and benzylamine',
    xp: 210,
  },
  {
    id: 'rx_balz_schiemann',
    name: 'Balz-Schiemann Reaction (Fluorobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'HBF4'],
    conditions: ['heat'],
    outputs: ['C6H5F', 'BF3', 'N2'],
    products: ['C6H5F', 'BF3', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + HBF₄ ──► C₆H₅N₂⁺BF₄⁻ ──(heat)──► C₆H₅F + BF₃ + N₂↑',
    type: 'Fluorination via Diazonium Fluoroborate',
    color: '#0ea5e9',
    observation: 'crystalline_ppt_then_gas',
    description: 'Precipitation of insoluble diazonium fluoroborate followed by dry thermal pyrolysis to yield fluorobenzene.',
    jeeRelevance: 'Exclusive laboratory method for aryl fluorides',
    xp: 240,
  },
  {
    id: 'rx_azo_coupling_phenol',
    name: 'Azo Coupling with Phenol (p-Hydroxyazobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'C6H5OH', 'NaOH'],
    conditions: ['ice_cold', 'ph_9_10'],
    outputs: ['orange_dye', 'NaCl', 'H2O'],
    products: ['orange_dye', 'NaCl', 'H2O'],
    equation: 'C₆H₅N₂⁺Cl⁻ + C₆H₅OH + NaOH ──(pH 9-10)──► p-Hydroxyazobenzene (Orange Dye) + NaCl + H₂O',
    type: 'Electrophilic Aromatic Substitution (Azo Coupling)',
    color: '#ea580c',
    observation: 'precipitate_orange',
    description: 'Formation of vibrant orange azo dye precipitate under mildly alkaline conditions (pH 9-10).',
    jeeRelevance: 'Flagship JEE Dye Test for primary aromatic amines',
    xp: 260,
  },
  {
    id: 'rx_azo_coupling_naphthol',
    name: 'Azo Coupling with β-Naphthol (Scarlet Red Dye)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'beta_naphthol', 'NaOH'],
    conditions: ['ice_cold', 'alkaline'],
    outputs: ['scarlet_red_dye', 'NaCl', 'H2O'],
    products: ['scarlet_red_dye', 'NaCl', 'H2O'],
    equation: 'C₆H₅N₂⁺Cl⁻ + β-Naphthol + NaOH ──► 1-(Phenylazo)-2-naphthol (Scarlet Red Dye)↓',
    type: 'Azo Dye Coupling',
    color: '#dc2626',
    observation: 'precipitate_red',
    description: 'Formation of an intense, insoluble scarlet red dye precipitate confirming aromatic diazonium cation.',
    jeeRelevance: 'Gold Standard Confirmatory Practical Test for Aniline',
    xp: 280,
  },
  {
    id: 'rx_aldol_condensation',
    name: 'Aldol Condensation of Acetaldehyde',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'NaOH'],
    conditions: ['dil_naoh', 'heat'],
    outputs: ['CH3CH=CHCHO', 'H2O'],
    products: ['CH3CH=CHCHO', 'H2O'],
    equation: '2CH₃CHO ──(dil. NaOH / heat)──► CH₃-CH=CH-CHO (Crotonaldehyde) + H₂O',
    type: 'Aldol Condensation & Dehydration',
    color: '#facc15',
    observation: 'pungent_liquid',
    description: 'Enolate addition of acetaldehyde followed by dehydration yields α,β-unsaturated aldehyde (crotonaldehyde).',
    jeeRelevance: 'Highest frequency JEE Advanced carbonyl reaction',
    xp: 270,
  },
  {
    id: 'rx_cannizzaro_benzaldehyde',
    name: 'Cannizzaro Disproportionation of Benzaldehyde',
    category: 'Aldehydes & Ketones',
    inputs: ['C6H5CHO', 'KOH'],
    conditions: ['conc_koh', '50_pct'],
    outputs: ['C6H5CH2OH', 'C6H5COOK'],
    products: ['C6H5CH2OH', 'C6H5COOK'],
    equation: '2C₆H₅CHO + 50% KOH ──► C₆H₅CH₂OH (Benzyl Alcohol) + C₆H₅COOK (Potassium Benzoate)',
    type: 'Redox Disproportionation',
    color: '#38bdf8',
    observation: 'two_layers_oily',
    description: 'Non-enolizable benzaldehyde undergoes self oxidation-reduction to produce benzyl alcohol and potassium benzoate.',
    jeeRelevance: 'Essential JEE question testing aldehydes without α-hydrogen',
    xp: 260,
  },
  {
    id: 'rx_tollens_test',
    name: "Tollens' Test (Silver Mirror Test)",
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'AgNO3', 'NH4OH', 'NaOH'],
    conditions: ['warm_water_bath'],
    outputs: ['Ag_mirror', 'CH3COONH4', 'H2O'],
    products: ['Ag_mirror', 'CH3COONH4', 'H2O'],
    equation: 'CH₃CHO + 2[Ag(NH₃)₂]⁺ + 3OH⁻ ──► CH₃COO⁻ + 2Ag↓ (Silver Mirror) + 4NH₃ + 2H₂O',
    type: 'Mild Oxidation & Silver Mirror Deposition',
    color: '#94a3b8',
    observation: 'silver_mirror',
    description: 'Aldehyde readily reduces Tollens reagent, depositing a gleaming metallic silver mirror coating on inner test tube walls.',
    jeeRelevance: 'Core diagnostic practical test distinguishing aldehydes from ketones',
    xp: 250,
  },
  {
    id: 'rx_fehling_test',
    name: "Fehling's Test for Aliphatic Aldehydes",
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'CuSO4', 'NaOH'],
    conditions: ['heat'],
    outputs: ['Cu2O', 'CH3COONa', 'H2O'],
    products: ['Cu2O', 'CH3COONa', 'H2O'],
    equation: 'CH₃CHO + 2Cu²⁺ + 5OH⁻ ──► Cu₂O↓ (Red Cuprous Oxide) + CH₃COO⁻ + 3H₂O',
    type: 'Copper Reduction Test',
    color: '#dc2626',
    observation: 'precipitate_red',
    description: 'Deep blue Fehling solution turns turbid green then forms an opaque brick-red cuprous oxide (Cu2O) precipitate.',
    jeeRelevance: 'Practical test separating aliphatic and aromatic aldehydes',
    xp: 240,
  },
  {
    id: 'rx_iodoform_acetone',
    name: 'Iodoform Reaction with Acetone',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3COCH3', 'I2', 'NaOH'],
    conditions: ['warm'],
    outputs: ['CHI3', 'CH3COONa', 'NaI', 'H2O'],
    products: ['CHI3', 'CH3COONa', 'NaI', 'H2O'],
    equation: 'CH₃COCH₃ + 3I₂ + 4NaOH ──► CHI₃↓ (Iodoform Yellow Crystals) + CH₃COONa + 3NaI + 3H₂O',
    type: 'Haloform Cleavage',
    color: '#eab308',
    observation: 'precipitate_yellow',
    description: 'Methyl carbonyl cleaves to yield bright canary-yellow crystals of triiodomethane (Iodoform) with characteristic antiseptic odor.',
    jeeRelevance: 'Primary JEE test for CH3-C=O and CH3-CH(OH)- groups',
    xp: 270,
  },
  {
    id: 'rx_finkelstein',
    name: 'Finkelstein Halogen Exchange',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3CH2Cl', 'NaI', 'acetone'],
    conditions: ['dry_acetone'],
    outputs: ['CH3CH2I', 'NaCl'],
    products: ['CH3CH2I', 'NaCl'],
    equation: 'CH₃CH₂Cl + NaI ──(dry acetone)──► CH₃CH₂I + NaCl↓',
    type: 'SN2 Halogen Exchange',
    color: '#cbd5e1',
    observation: 'white_precipitate_nacl',
    description: 'Precipitation of insoluble NaCl in dry acetone drives equilibrium forward to produce ethyl iodide.',
    jeeRelevance: 'Classic Class 12 haloalkane synthesis',
    xp: 230,
  },
  {
    id: 'rx_swarts',
    name: 'Swarts Fluorination Reaction',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3Br', 'AgF'],
    conditions: ['heat'],
    outputs: ['CH3F', 'AgBr'],
    products: ['CH3F', 'AgBr'],
    equation: 'CH₃Br + AgF ──► CH₃F + AgBr↓ (Pale Yellow)',
    type: 'Fluoride Exchange',
    color: '#fef08a',
    observation: 'pale_yellow_precipitate',
    description: 'Heavy metal fluoride exchanges halogen to generate methyl fluoride and pale-yellow silver bromide precipitate.',
    jeeRelevance: 'Standard inorganic fluoride exchange in NCERT',
    xp: 230,
  },
  {
    id: 'rx_wurtz_coupling',
    name: 'Wurtz Alkane Coupling',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3Br', 'Na', 'dry_ether'],
    conditions: ['dry_ether'],
    outputs: ['C2H6', 'NaBr'],
    products: ['C2H6', 'NaBr'],
    equation: '2CH₃Br + 2Na ──(dry ether)──► CH₃-CH₃ (Ethane) + 2NaBr',
    type: 'Organometallic Radical Coupling',
    color: '#94a3b8',
    observation: 'gas_evolution_and_salt',
    description: 'Sodium coupling in anhydrous ether couples alkyl radicals to synthesize symmetrical higher alkanes.',
    jeeRelevance: 'Core Hydrocarbon synthesis mechanism',
    xp: 220,
  },
  {
    id: 'rx_wurtz_fittig',
    name: 'Wurtz-Fittig Alkylarene Synthesis',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['C6H5Br', 'CH3Br', 'Na', 'dry_ether'],
    conditions: ['dry_ether'],
    outputs: ['C6H5CH3', 'NaBr'],
    products: ['C6H5CH3', 'NaBr'],
    equation: 'C₆H₅Br + CH₃Br + 2Na ──(dry ether)──► C₆H₅CH₃ (Toluene) + 2NaBr',
    type: 'Alkyl-Aryl Coupling',
    color: '#38bdf8',
    observation: 'clear_organic_liquid',
    description: 'Cross-coupling of aryl and alkyl halides mediated by metallic sodium to produce alkylated benzene rings.',
    jeeRelevance: 'Class 12 Haloarenes synthesis',
    xp: 240,
  },
  {
    id: 'rx_fittig_diphenyl',
    name: 'Fittig Diphenyl Coupling',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['C6H5Cl', 'Na', 'dry_ether'],
    conditions: ['dry_ether'],
    outputs: ['biphenyl', 'NaCl'],
    products: ['biphenyl', 'NaCl'],
    equation: '2C₆H₅Cl + 2Na ──(dry ether)──► C₆H₅-C₆H₅ (Biphenyl) + 2NaCl',
    type: 'Aryl Radical Dimerization',
    color: '#e2e8f0',
    observation: 'white_crystalline_solid',
    description: 'Coupling of two chlorobenzene molecules produces solid biphenyl.',
    jeeRelevance: 'Classic NCERT haloarene coupling',
    xp: 230,
  },
  {
    id: 'rx_clemmensen_reduction',
    name: 'Clemmensen Reduction of Acetone',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3COCH3', 'Zn_Hg', 'HCl'],
    conditions: ['reflux', 'conc_hcl'],
    outputs: ['C3H8', 'H2O', 'ZnCl2'],
    products: ['C3H8', 'H2O', 'ZnCl2'],
    equation: 'CH₃COCH₃ + 4[H] ──(Zn-Hg / conc. HCl)──► CH₃CH₂CH₃ (Propane) + H₂O',
    type: 'Carbonyl to Methylene Reduction',
    color: '#bae6fd',
    observation: 'gas_evolution_alkane',
    description: 'Amalgamated zinc in concentrated hydrochloric acid reduces carbonyl >C=O completely to methylene -CH2-.',
    jeeRelevance: 'Acid-stable carbonyl reduction method',
    xp: 260,
  },
  {
    id: 'rx_wolff_kishner',
    name: 'Wolff-Kishner Reduction of Acetophenone',
    category: 'Aldehydes & Ketones',
    inputs: ['C6H5COCH3', 'NH2NH2', 'KOH'],
    conditions: ['glycol', 'heat_180C'],
    outputs: ['C6H5CH2CH3', 'N2', 'H2O'],
    products: ['C6H5CH2CH3', 'N2', 'H2O'],
    equation: 'C₆H₅COCH₃ + NH₂NH₂ ──(KOH / ethylene glycol / heat)──► C₆H₅CH₂CH₃ (Ethylbenzene) + N₂↑',
    type: 'Base-Catalyzed Hydrazone Reduction',
    color: '#38bdf8',
    observation: 'nitrogen_gas_evolution',
    description: 'Hydrazone intermediate decomposes under strong alkaline conditions to yield ethylbenzene and nitrogen gas.',
    jeeRelevance: 'Base-stable reduction complementary to Clemmensen',
    xp: 260,
  },
  {
    id: 'rx_reimer_tiemann',
    name: 'Reimer-Tiemann Salicylaldehyde Synthesis',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['C6H5OH', 'CHCl3', 'NaOH'],
    conditions: ['heat_60C'],
    outputs: ['salicylaldehyde', 'NaCl', 'H2O'],
    products: ['salicylaldehyde', 'NaCl', 'H2O'],
    equation: 'C₆H₅OH + CHCl₃ + 3NaOH ──► o-HOC₆H₄CHO (Salicylaldehyde) + 3NaCl + 2H₂O',
    type: 'Dichlorocarbene Electrophilic Aromatic Substitution',
    color: '#eab308',
    observation: 'yellow_fragrant_liquid',
    description: 'Electrophilic attack of generated dichlorocarbene (:CCl2) on phenoxide ring yields ortho-formylated salicylaldehyde.',
    jeeRelevance: 'Classic carbene mechanism in JEE Advanced',
    xp: 280,
  },
  {
    id: 'rx_kolbe_schmitt',
    name: "Kolbe's Synthesis of Salicylic Acid",
    category: 'General Organic Chemistry (GOC)',
    inputs: ['C6H5OH', 'NaOH', 'CO2'],
    conditions: ['pressure_4_7atm', 'heat_140C'],
    outputs: ['salicylic_acid'],
    products: ['salicylic_acid'],
    equation: 'C₆H₅ONa + CO₂ ──(140°C / 4-7 atm)──► o-HOC₆H₄COOH (Salicylic Acid)',
    type: 'Carboxylation of Phenoxide',
    color: '#f8fafc',
    observation: 'white_crystals',
    description: 'Phenoxide ring undergoes nucleophilic addition to carbon dioxide yielding precursor to aspirin.',
    jeeRelevance: 'Aspirin industrial synthesis in Class 12',
    xp: 270,
  },
  {
    id: 'rx_gabriel_phthalimide',
    name: 'Gabriel Phthalimide Synthesis of Primary Amines',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['phthalimide', 'KOH', 'CH3CH2Br'],
    conditions: ['heat'],
    outputs: ['CH3CH2NH2', 'phthalic_acid'],
    products: ['CH3CH2NH2', 'phthalic_acid'],
    equation: 'Phthalimide + KOH + CH₃CH₂Br ──► CH₃CH₂NH₂ (Ethylamine) + Potassium Phthalate',
    type: 'SN2 Alkylation & Hydrazine Cleavage',
    color: '#f1f5f9',
    observation: 'ammoniacal_odor',
    description: 'Exclusive route to pure 1° aliphatic amines free from secondary or tertiary contamination.',
    jeeRelevance: 'Crucial JEE method distinguishing 1° amines',
    xp: 270,
  },
  {
    id: 'rx_hoffmann_bromamide',
    name: 'Hoffmann Bromamide Degradation',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['CH3CONH2', 'Br2', 'NaOH'],
    conditions: ['heat'],
    outputs: ['CH3NH2', 'Na2CO3', 'NaBr', 'H2O'],
    products: ['CH3NH2', 'Na2CO3', 'NaBr', 'H2O'],
    equation: 'CH₃CONH₂ + Br₂ + 4NaOH ──(heat)──► CH₃NH₂ (Methylamine) + Na₂CO₃ + 2NaBr + 2H₂O',
    type: 'Isocyanate Rearrangement Step-Down Degradation',
    color: '#e0f2fe',
    observation: 'fishy_gas_evolution',
    description: 'Step-down degradation of amide yielding primary amine containing one carbon atom fewer.',
    jeeRelevance: 'High-frequency chain-shortening conversion in organic problem solving',
    xp: 280,
  },
  {
    id: 'rx_carbylamine_test',
    name: 'Carbylamine Test for Primary Amines',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['C2H5NH2', 'CHCl3', 'KOH'],
    conditions: ['heat'],
    outputs: ['C2H5NC', 'KCl', 'H2O'],
    products: ['C2H5NC', 'KCl', 'H2O'],
    equation: 'C₂H₅NH₂ + CHCl₃ + 3KOH ──(heat)──► C₂H₅NC (Ethyl Isocyanide) + 3KCl + 3H₂O',
    type: 'Isocyanide Reaction',
    color: '#cbd5e1',
    observation: 'extremely_foul_odor',
    description: 'Heating 1° amine with chloroform and alcoholic KOH produces an extremely offensive, nauseating isocyanide odor.',
    jeeRelevance: 'Absolute diagnostic test for primary amines in laboratory exams',
    xp: 290,
  },
  {
    id: 'rx_chromyl_chloride',
    name: 'Chromyl Chloride Test for Chloride',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NaCl', 'K2Cr2O7', 'H2SO4'],
    conditions: ['heat'],
    outputs: ['CrO2Cl2', 'KHSO4', 'NaHSO4', 'H2O'],
    products: ['CrO2Cl2', 'KHSO4', 'NaHSO4', 'H2O'],
    equation: '4NaCl + K₂Cr₂O₇ + 6H₂SO₄ ──(heat)──► 2CrO₂Cl₂↑ (Reddish-Brown Vapor) + 2KHSO₄ + 4NaHSO₄ + 3H₂O',
    type: 'Volatile Oxychloride Generation',
    color: '#ea580c',
    observation: 'reddish_brown_vapors',
    description: 'Heating dry chloride salt with dichromate and conc. sulfuric acid releases dense, suffocating reddish-orange CrO2Cl2 vapors.',
    jeeRelevance: 'Famous test distinguishing ionic chlorides from covalent ones',
    xp: 290,
  },
  {
    id: 'rx_brown_ring_test',
    name: 'Brown Ring Test for Nitrate (NO3-)',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NaNO3', 'FeSO4', 'H2SO4'],
    conditions: ['cold', 'slow_addition'],
    outputs: ['[Fe(H2O)5(NO)]SO4'],
    products: ['[Fe(H2O)5(NO)]SO4'],
    equation: 'NO₃⁻ + 3Fe²⁺ + 4H⁺ ──► NO + 3Fe³⁺ + 2H₂O; [Fe(H₂O)₆]²⁺ + NO ──► [Fe(H₂O)₅(NO)]²⁺ (Brown Ring)',
    type: 'Nitrosyl Complexation',
    color: '#78350f',
    observation: 'brown_ring_junction',
    description: 'A delicate brown ring of pentaaquanitrosyliron(II) complex forms at junction of the two liquid layers.',
    jeeRelevance: 'Iconic Class 12 inorganic practical test for nitrate',
    xp: 290,
  },
  {
    id: 'rx_nessler_ammonia',
    name: "Nessler's Reagent Test for Ammonia",
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NH4Cl', 'K2HgI4', 'KOH'],
    conditions: ['alkaline'],
    outputs: ['HgO_HgNH2I', 'KI', 'KCl', 'H2O'],
    products: ['HgO_HgNH2I', 'KI', 'KCl', 'H2O'],
    equation: '2K₂[HgI₄] + NH₃ + 3KOH ──► H₂N-Hg-O-Hg-I↓ (Iodide of Millon Base / Brown ppt) + 7KI + 2H₂O',
    type: 'Heavy Metal Complex Precipitation',
    color: '#92400e',
    observation: 'precipitate_brown',
    description: 'Alkaline Nesslers reagent turns yellowish-brown or yields a deep brown precipitate in presence of ammonium ions.',
    jeeRelevance: 'Classic Group 0 zero-group ammonium test in qualitative salt analysis',
    xp: 270,
  },
];
`;

console.log('Building combinatorial generators for over 5,000 reactions...');
`;

// Now let's execute the node script to write the combined dataset
`;
