// Frontend chemical & apparatus catalog for Chemistry Workspace.
// Integrates all 118 Anime Elements, key Organic Compounds (Diazonium, Haloalkanes, Aldehydes, Ketones, Benzene),
// Laboratory Apparatus (Beakers, Test Tubes, Bunsen Burner Fire Equipment), and Action Arrows.

import { ALL_118_ELEMENTS } from './data/elementsAnimeData.js';

export const APPARATUS_ITEMS = [
  { id: 'app_beaker_250', name: 'Beaker (250 mL)', capacity: 250, type: 'beaker', icon: '🧪', desc: 'Standard borosilicate glass beaker for mixing & heating' },
  { id: 'app_beaker_500', name: 'Beaker (500 mL)', capacity: 500, type: 'beaker', icon: '🍶', desc: 'Large capacity beaker for exothermic bulk reactions' },
  { id: 'app_test_tube', name: 'Test Tube (50 mL)', capacity: 50, type: 'test_tube', icon: '🧪', desc: 'Slender cylindrical tube mounted in wooden/acrylic rack' },
  { id: 'app_erlenmeyer', name: 'Erlenmeyer Flask', capacity: 250, type: 'flask', icon: '⚗️', desc: 'Conical neck flask ideal for swirling without spillage' },
  { id: 'app_bunsen_burner', name: 'Bunsen Burner ("Fire Fire")', type: 'burner', icon: '🔥', desc: 'Dual-flame thermal source: Luminous Yellow vs Roaring Sky Blue flame' },
  { id: 'app_pipette', name: 'Precision Dropper / Pipette', type: 'dropper', icon: '💧', desc: 'Accurately delivers drops of liquid reagent into vessels' },
  { id: 'app_glass_stirrer', name: 'Glass Stirring Rod', type: 'stirrer', icon: '🪄', desc: 'Agitates solution to accelerate diffusion and reaction kinetics' },
];

export const CATEGORIES = [
  'All',
  'Organic Chemistry',
  '118 Elements (Anime)',
  'Diazonium & Benzene',
  'Aldehydes & Ketones',
  'Haloalkanes & Alkyls',
  'Acids',
  'Bases',
  'Salts & Reagents',
  'Gases',
  'Action Arrows',
];

export const ORGANIC_SUBGROUPS = [
  { id: 'all', label: 'All Organic' },
  { id: 'diazonium', label: 'Diazonium' },
  { id: 'benzene', label: 'Benzene' },
  { id: 'aldehydes', label: 'Aldehydes' },
  { id: 'ketones', label: 'Ketones' },
  { id: 'haloalkanes', label: 'Haloalkanes' },
];

// Convert 118 elements into palette materials with search indexing
const ELEMENT_MATERIALS = ALL_118_ELEMENTS.map((el) => {
  const isMg = el.symbol.toLowerCase() === 'mg';
  const isO = el.symbol.toLowerCase() === 'o';
  return {
    id: `el_${el.symbol.toLowerCase()}`,
    formula: el.symbol,
    name: `${el.name} (${el.animeTitle.split('(')[0].trim()})`,
    rawName: el.name,
    category: '118 Elements (Anime)',
    phase: el.category.includes('Gas') ? 'g' : el.symbol === 'Hg' || el.symbol === 'Br' ? 'l' : 's',
    tone: 'from-sky-100 to-amber-200',
    number: el.number,
    affinity: el.affinity,
    animeTitle: el.animeTitle,
    power: el.power,
    reactivity: el.reactivity,
    keywords: [
      el.name.toLowerCase(),
      el.symbol.toLowerCase(),
      el.category.toLowerCase(),
      el.affinity.toLowerCase(),
      ...(isMg ? ['magnesium', 'mg', 'ribbon', 'metal', 'white light', 'white ash', 'mgo'] : []),
      ...(isO ? ['oxygen', 'o', 'o2', 'air', 'combustion', 'gas'] : []),
    ],
  };
});

export const MATERIAL_CHEMICALS = [
  // --- Class 10 High Priority Experiment Reactants ---
  {
    id: 'mat_mg_ribbon',
    formula: 'Mg',
    name: 'Magnesium (Ribbon)',
    rawName: 'Magnesium',
    category: 'Salts & Reagents',
    phase: 's',
    tone: 'from-slate-100 to-slate-300',
    keywords: ['magnesium', 'mg', 'ribbon', 'metal', 'white ash', 'mgo', 'combustion', 'dazzling'],
  },
  {
    id: 'mat_o2_gas',
    formula: 'O2',
    name: 'Oxygen Gas (O2)',
    rawName: 'Oxygen',
    category: 'Gases',
    phase: 'g',
    tone: 'from-cyan-100 to-sky-300',
    keywords: ['oxygen', 'o2', 'o', 'gas', 'air', 'combustion', 'oxidizer'],
  },
  {
    id: 'mat_mgo_ash',
    formula: 'MgO',
    name: 'Magnesium Oxide (White Ash)',
    rawName: 'Magnesium Oxide',
    category: 'Salts & Reagents',
    phase: 's',
    tone: 'from-white to-slate-200',
    keywords: ['magnesium oxide', 'mgo', 'white ash', 'ash', 'oxide'],
  },

  // --- Organic Chemistry: Diazonium Group ---
  {
    id: 'c6h5n2cl',
    formula: 'C6H5N2Cl',
    name: 'Benzene Diazonium Chloride',
    category: 'Diazonium & Benzene',
    organicGroup: 'diazonium',
    phase: 'aq',
    tone: 'from-sky-200 to-blue-400',
    keywords: ['diazonium', 'benzene diazonium chloride', 'sandmeyer', 'azo', 'c6h5n2cl'],
  },
  {
    id: 'p_no2_c6h4n2cl',
    formula: 'p-NO2-C6H4N2Cl',
    name: 'p-Nitrobenzene Diazonium Chloride',
    category: 'Diazonium & Benzene',
    organicGroup: 'diazonium',
    phase: 'aq',
    tone: 'from-yellow-200 to-amber-400',
    keywords: ['diazonium', 'nitro', 'coupling', 'dye'],
  },
  {
    id: 'p_ch3_c6h4n2cl',
    formula: 'p-CH3-C6H4N2Cl',
    name: 'p-Toluene Diazonium Chloride',
    category: 'Diazonium & Benzene',
    organicGroup: 'diazonium',
    phase: 'aq',
    tone: 'from-sky-100 to-blue-300',
    keywords: ['diazonium', 'toluene diazonium', 'sandmeyer'],
  },
  {
    id: 'c6h5n2bf4',
    formula: 'C6H5N2BF4',
    name: 'Benzene Diazonium Fluoroborate',
    category: 'Diazonium & Benzene',
    organicGroup: 'diazonium',
    phase: 's',
    tone: 'from-slate-100 to-sky-200',
    keywords: ['diazonium', 'balz-schiemann', 'fluoroborate', 'fluorobenzene'],
  },

  // --- Organic Chemistry: Benzene & Aromatic Group ---
  {
    id: 'c6h6',
    formula: 'C6H6',
    name: 'Benzene',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-slate-200 to-slate-400',
    keywords: ['benzene', 'c6h6', 'aromatic', 'ring', 'hydrocarbon'],
  },
  {
    id: 'c6h5nh2',
    formula: 'C6H5NH2',
    name: 'Aniline (Aminobenzene)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-amber-200 to-amber-400',
    keywords: ['aniline', 'c6h5nh2', 'benzene', 'amine', 'diazotization'],
  },
  {
    id: 'c6h5oh',
    formula: 'C6H5OH',
    name: 'Phenol (Carbolic Acid)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 's',
    tone: 'from-rose-100 to-rose-300',
    keywords: ['phenol', 'c6h5oh', 'benzene', 'carbolic acid', 'kolbe', 'reimer-tiemann'],
  },
  {
    id: 'c6h5no2',
    formula: 'C6H5NO2',
    name: 'Nitrobenzene (Oil of Mirbane)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-yellow-200 to-yellow-400',
    keywords: ['nitrobenzene', 'c6h5no2', 'benzene', 'oil of mirbane', 'nitration'],
  },
  {
    id: 'c6h5cl',
    formula: 'C6H5Cl',
    name: 'Chlorobenzene',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-sky-200 to-slate-400',
    keywords: ['chlorobenzene', 'c6h5cl', 'benzene', 'haloarene', 'sandmeyer'],
  },
  {
    id: 'c6h5br',
    formula: 'C6H5Br',
    name: 'Bromobenzene',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-amber-300 to-orange-500',
    keywords: ['bromobenzene', 'c6h5br', 'benzene', 'haloarene', 'sandmeyer'],
  },
  {
    id: 'c6h5i',
    formula: 'C6H5I',
    name: 'Iodobenzene',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-slate-300 to-slate-600',
    keywords: ['iodobenzene', 'c6h5i', 'benzene', 'haloarene'],
  },
  {
    id: 'c6h5f',
    formula: 'C6H5F',
    name: 'Fluorobenzene',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-sky-100 to-sky-300',
    keywords: ['fluorobenzene', 'c6h5f', 'benzene', 'balz-schiemann'],
  },
  {
    id: 'c6h5cn',
    formula: 'C6H5CN',
    name: 'Benzonitrile (Cyanobenzene)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-slate-200 to-slate-400',
    keywords: ['benzonitrile', 'c6h5cn', 'benzene', 'nitrile', 'cyanide'],
  },
  {
    id: 'c6h5ch3',
    formula: 'C6H5CH3',
    name: 'Toluene (Methylbenzene)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 'l',
    tone: 'from-sky-100 to-sky-300',
    keywords: ['toluene', 'c6h5ch3', 'benzene', 'methylbenzene', 'etard'],
  },
  {
    id: 'c6h5cooh',
    formula: 'C6H5COOH',
    name: 'Benzoic Acid',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 's',
    tone: 'from-slate-50 to-slate-200',
    keywords: ['benzoic acid', 'c6h5cooh', 'benzene', 'carboxylic acid'],
  },
  {
    id: 'salicylic_acid',
    formula: 'salicylic_acid',
    name: 'Salicylic Acid (Aspirin Precursor)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 's',
    tone: 'from-slate-50 to-slate-200',
    keywords: ['salicylic acid', 'aspirin', 'benzene', 'kolbe', 'phenol'],
  },
  {
    id: 'beta_naphthol',
    formula: 'beta_naphthol',
    name: 'β-Naphthol (2-Naphthol)',
    category: 'Diazonium & Benzene',
    organicGroup: 'benzene',
    phase: 's',
    tone: 'from-red-100 to-rose-300',
    keywords: ['beta-naphthol', 'naphthol', 'dye test', 'azo coupling', 'scarlet red dye'],
  },

  // --- Organic Chemistry: Aldehydes Group ---
  {
    id: 'ch3cho',
    formula: 'CH3CHO',
    name: 'Acetaldehyde (Ethanal)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'l',
    tone: 'from-yellow-100 to-amber-300',
    keywords: ['acetaldehyde', 'ethanal', 'ch3cho', 'aldehyde', 'aldol', 'tollens', 'fehling'],
  },
  {
    id: 'c6h5cho',
    formula: 'C6H5CHO',
    name: 'Benzaldehyde (Oil of Bitter Almonds)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'l',
    tone: 'from-amber-200 to-orange-300',
    keywords: ['benzaldehyde', 'c6h5cho', 'aldehyde', 'cannizzaro', 'benzoin', 'almonds'],
  },
  {
    id: 'hcho',
    formula: 'HCHO',
    name: 'Formaldehyde (Methanal / Formalin)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'g',
    tone: 'from-slate-100 to-sky-200',
    keywords: ['formaldehyde', 'methanal', 'hcho', 'aldehyde', 'formalin', 'cannizzaro'],
  },
  {
    id: 'c2h5cho',
    formula: 'C2H5CHO',
    name: 'Propionaldehyde (Propanal)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'l',
    tone: 'from-yellow-50 to-amber-200',
    keywords: ['propionaldehyde', 'propanal', 'c2h5cho', 'aldehyde'],
  },
  {
    id: 'salicylaldehyde',
    formula: 'salicylaldehyde',
    name: 'Salicylaldehyde (o-Formylphenol)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'l',
    tone: 'from-yellow-200 to-amber-400',
    keywords: ['salicylaldehyde', 'reimer-tiemann', 'aldehyde', 'fragrance'],
  },
  {
    id: 'crotonaldehyde',
    formula: 'CH3CH=CHCHO',
    name: 'Crotonaldehyde',
    category: 'Aldehydes & Ketones',
    organicGroup: 'aldehydes',
    phase: 'l',
    tone: 'from-amber-100 to-orange-300',
    keywords: ['crotonaldehyde', 'aldol condensation', 'aldehyde', 'unsaturated'],
  },

  // --- Organic Chemistry: Ketones Group ---
  {
    id: 'ch3coch3',
    formula: 'CH3COCH3',
    name: 'Acetone (Propanone)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'ketones',
    phase: 'l',
    tone: 'from-sky-100 to-sky-300',
    keywords: ['acetone', 'propanone', 'ch3coch3', 'ketone', 'iodoform', 'clemmensen', 'solvent'],
  },
  {
    id: 'c6h5coch3',
    formula: 'C6H5COCH3',
    name: 'Acetophenone (Methyl Phenyl Ketone)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'ketones',
    phase: 'l',
    tone: 'from-slate-100 to-slate-300',
    keywords: ['acetophenone', 'c6h5coch3', 'ketone', 'wolff-kishner', 'iodoform'],
  },
  {
    id: 'c6h5coc6h5',
    formula: 'C6H5COC6H5',
    name: 'Benzophenone (Diphenyl Ketone)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'ketones',
    phase: 's',
    tone: 'from-slate-100 to-slate-300',
    keywords: ['benzophenone', 'c6h5coc6h5', 'ketone', 'diphenyl'],
  },
  {
    id: 'c2h5coch3',
    formula: 'C2H5COCH3',
    name: 'Ethyl Methyl Ketone (Butanone / MEK)',
    category: 'Aldehydes & Ketones',
    organicGroup: 'ketones',
    phase: 'l',
    tone: 'from-sky-100 to-blue-200',
    keywords: ['butanone', 'mek', 'c2h5coch3', 'ketone', 'iodoform'],
  },
  {
    id: 'cyclohexanone',
    formula: 'cyclohexanone',
    name: 'Cyclohexanone',
    category: 'Aldehydes & Ketones',
    organicGroup: 'ketones',
    phase: 'l',
    tone: 'from-slate-100 to-slate-300',
    keywords: ['cyclohexanone', 'cyclic ketone', 'oxime', 'nylon'],
  },

  // --- Organic Chemistry: Haloalkanes & Alkyls Group ---
  {
    id: 'ch3cl',
    formula: 'CH3Cl',
    name: 'Methyl Chloride (Chloromethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'g',
    tone: 'from-sky-200 to-blue-300',
    keywords: ['methyl chloride', 'chloromethane', 'ch3cl', 'haloalkane', 'wurtz', 'finkelstein'],
  },
  {
    id: 'ch3br',
    formula: 'CH3Br',
    name: 'Methyl Bromide (Bromomethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'g',
    tone: 'from-amber-200 to-amber-400',
    keywords: ['methyl bromide', 'bromomethane', 'ch3br', 'haloalkane', 'swarts'],
  },
  {
    id: 'ch3i',
    formula: 'CH3I',
    name: 'Methyl Iodide (Iodomethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-yellow-200 to-yellow-500',
    keywords: ['methyl iodide', 'iodomethane', 'ch3i', 'haloalkane', 'finkelstein'],
  },
  {
    id: 'c2h5cl',
    formula: 'C2H5Cl',
    name: 'Ethyl Chloride (Chloroethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'g',
    tone: 'from-sky-100 to-sky-300',
    keywords: ['ethyl chloride', 'chloroethane', 'c2h5cl', 'haloalkane'],
  },
  {
    id: 'c2h5br',
    formula: 'C2H5Br',
    name: 'Ethyl Bromide (Bromoethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-amber-100 to-amber-300',
    keywords: ['ethyl bromide', 'bromoethane', 'c2h5br', 'haloalkane', 'wurtz'],
  },
  {
    id: 'c2h5i',
    formula: 'C2H5I',
    name: 'Ethyl Iodide (Iodoethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-yellow-100 to-yellow-400',
    keywords: ['ethyl iodide', 'iodoethane', 'c2h5i', 'haloalkane'],
  },
  {
    id: 'chcl3',
    formula: 'CHCl3',
    name: 'Chloroform (Trichloromethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-slate-200 to-slate-400',
    keywords: ['chloroform', 'trichloromethane', 'chcl3', 'haloalkane', 'carbylamine', 'reimer-tiemann'],
  },
  {
    id: 'ccl4',
    formula: 'CCl4',
    name: 'Carbon Tetrachloride (Tetrachloromethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-slate-300 to-slate-500',
    keywords: ['carbon tetrachloride', 'ccl4', 'haloalkane', 'solvent'],
  },
  {
    id: 'chi3',
    formula: 'CHI3',
    name: 'Iodoform (Triiodomethane)',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 's',
    tone: 'from-yellow-300 to-amber-400',
    keywords: ['iodoform', 'chi3', 'yellow crystals', 'haloform', 'antiseptic'],
  },
  {
    id: 'c6h5ch2cl',
    formula: 'C6H5CH2Cl',
    name: 'Benzyl Chloride',
    category: 'Haloalkanes & Alkyls',
    organicGroup: 'haloalkanes',
    phase: 'l',
    tone: 'from-slate-200 to-slate-400',
    keywords: ['benzyl chloride', 'c6h5ch2cl', 'haloalkane', 'benzylic'],
  },

  // --- Acids ---
  { id: 'hcl', formula: 'HCl', name: 'Hydrochloric Acid', category: 'Acids', phase: 'aq', tone: 'from-rose-300 to-rose-500', keywords: ['hcl', 'hydrochloric acid', 'acid'] },
  { id: 'h2so4', formula: 'H2SO4', name: 'Sulphuric Acid (King of Chemicals)', category: 'Acids', phase: 'aq', tone: 'from-amber-200 to-amber-400', keywords: ['h2so4', 'sulphuric acid', 'acid', 'vitriol'] },
  { id: 'hno3', formula: 'HNO3', name: 'Nitric Acid', category: 'Acids', phase: 'aq', tone: 'from-yellow-100 to-yellow-300', keywords: ['hno3', 'nitric acid', 'acid', 'aqua fortis'] },
  { id: 'ch3cooh', formula: 'CH3COOH', name: 'Acetic Acid (Ethanoic / Vinegar)', category: 'Acids', phase: 'aq', tone: 'from-orange-200 to-orange-400', keywords: ['ch3cooh', 'acetic acid', 'vinegar', 'ethanoic'] },
  { id: 'h3po4', formula: 'H3PO4', name: 'Phosphoric Acid', category: 'Acids', phase: 'aq', tone: 'from-teal-200 to-cyan-400', keywords: ['h3po4', 'phosphoric acid'] },
  { id: 'h3po2', formula: 'H3PO2', name: 'Hypophosphorous Acid', category: 'Acids', phase: 'aq', tone: 'from-sky-200 to-blue-300', keywords: ['h3po2', 'hypophosphorous'] },
  { id: 'hbf4', formula: 'HBF4', name: 'Fluoroboric Acid', category: 'Acids', phase: 'aq', tone: 'from-sky-100 to-sky-300', keywords: ['hbf4', 'fluoroboric'] },

  // --- Bases ---
  { id: 'naoh', formula: 'NaOH', name: 'Sodium Hydroxide (Caustic Soda)', category: 'Bases', phase: 'aq', tone: 'from-sky-200 to-sky-400', keywords: ['naoh', 'sodium hydroxide', 'base', 'caustic soda'] },
  { id: 'koh', formula: 'KOH', name: 'Potassium Hydroxide (Caustic Potash)', category: 'Bases', phase: 'aq', tone: 'from-sky-100 to-sky-300', keywords: ['koh', 'potassium hydroxide', 'base'] },
  { id: 'nh4oh', formula: 'NH4OH', name: 'Ammonium Hydroxide (Ammonia Solution)', category: 'Bases', phase: 'aq', tone: 'from-cyan-100 to-cyan-300', keywords: ['nh4oh', 'ammonium hydroxide', 'base'] },
  { id: 'caoh2', formula: 'Ca(OH)2', name: 'Calcium Hydroxide (Slaked Lime / Limewater)', category: 'Bases', phase: 'aq', tone: 'from-slate-100 to-slate-200', keywords: ['ca(oh)2', 'calcium hydroxide', 'slaked lime', 'limewater'] },
  { id: 'mgoh2', formula: 'Mg(OH)2', name: 'Magnesium Hydroxide (Milk of Magnesia)', category: 'Bases', phase: 's', tone: 'from-teal-100 to-teal-300', keywords: ['mg(oh)2', 'magnesium hydroxide', 'antacid', 'milk of magnesia'] },

  // --- Salts & Laboratory Reagents ---
  { id: 'nano2', formula: 'NaNO2', name: 'Sodium Nitrite', category: 'Salts & Reagents', phase: 's', tone: 'from-yellow-100 to-yellow-200', keywords: ['nano2', 'sodium nitrite', 'diazotization'] },
  { id: 'cucl', formula: 'CuCl', name: 'Copper(I) Chloride (Cuprous Chloride)', category: 'Salts & Reagents', phase: 's', tone: 'from-emerald-200 to-emerald-400', keywords: ['cucl', 'sandmeyer'] },
  { id: 'cubr', formula: 'CuBr', name: 'Copper(I) Bromide', category: 'Salts & Reagents', phase: 's', tone: 'from-amber-200 to-amber-400', keywords: ['cubr', 'sandmeyer'] },
  { id: 'cucn', formula: 'CuCN', name: 'Copper(I) Cyanide', category: 'Salts & Reagents', phase: 's', tone: 'from-slate-200 to-slate-300', keywords: ['cucn', 'sandmeyer cyanation'] },
  { id: 'ki', formula: 'KI', name: 'Potassium Iodide', category: 'Salts & Reagents', phase: 'aq', tone: 'from-slate-100 to-slate-300', keywords: ['ki', 'potassium iodide'] },
  { id: 'alcl3', formula: 'AlCl3', name: 'Anhydrous Aluminium Chloride', category: 'Salts & Reagents', phase: 's', tone: 'from-slate-100 to-slate-200', keywords: ['alcl3', 'friedel-crafts', 'lewis acid'] },
  { id: 'fecl3', formula: 'FeCl3', name: 'Iron(III) Chloride (Neutral FeCl3)', category: 'Salts & Reagents', phase: 'aq', tone: 'from-amber-300 to-amber-500', keywords: ['fecl3', 'ferric chloride', 'phenol test'] },
  { id: 'agno3', formula: 'AgNO3', name: 'Silver Nitrate (Lunar Caustic)', category: 'Salts & Reagents', phase: 'aq', tone: 'from-slate-100 to-slate-200', keywords: ['agno3', 'silver nitrate', 'tollens', 'halide test'] },
  { id: 'kmno4', formula: 'KMnO4', name: 'Potassium Permanganate', category: 'Salts & Reagents', phase: 'aq', tone: 'from-sky-300 to-blue-500', keywords: ['kmno4', 'permanganate', 'baeyer', 'oxidizing agent'] },
  { id: 'k2cr2o7', formula: 'K2Cr2O7', name: 'Potassium Dichromate', category: 'Salts & Reagents', phase: 'aq', tone: 'from-orange-300 to-amber-500', keywords: ['k2cr2o7', 'dichromate', 'chromyl chloride'] },
  { id: 'feso4', formula: 'FeSO4', name: 'Ferrous Sulphate (Green Vitriol)', category: 'Salts & Reagents', phase: 'aq', tone: 'from-emerald-300 to-emerald-500', keywords: ['feso4', 'ferrous sulphate', 'brown ring'] },
  { id: 'k2hgi4', formula: 'K2HgI4', name: "Nessler's Reagent", category: 'Salts & Reagents', phase: 'aq', tone: 'from-amber-200 to-yellow-400', keywords: ['nessler', 'ammonia test'] },
  { id: 'dmg', formula: 'DMG', name: 'Dimethylglyoxime', category: 'Salts & Reagents', phase: 's', tone: 'from-rose-200 to-red-400', keywords: ['dmg', 'nickel test'] },
  { id: 'caco3', formula: 'CaCO3', name: 'Calcium Carbonate (Limestone / Marble)', category: 'Salts & Reagents', phase: 's', tone: 'from-slate-100 to-slate-200', keywords: ['caco3', 'limestone', 'marble', 'chalk'] },
  { id: 'nahco3', formula: 'NaHCO3', name: 'Sodium Bicarbonate (Baking Soda)', category: 'Salts & Reagents', phase: 's', tone: 'from-slate-50 to-slate-200', keywords: ['nahco3', 'baking soda', 'effervescence'] },
  { id: 'nacl', formula: 'NaCl', name: 'Sodium Chloride (Common Salt)', category: 'Salts & Reagents', phase: 'aq', tone: 'from-slate-100 to-slate-300', keywords: ['nacl', 'salt'] },
  { id: 'cuso4', formula: 'CuSO4', name: 'Copper Sulphate (Blue Vitriol)', category: 'Salts & Reagents', phase: 'aq', tone: 'from-sky-300 to-blue-500', keywords: ['cuso4', 'blue vitriol', 'fehling'] },
  { id: 'zn_hg', formula: 'Zn_Hg', name: 'Zinc Amalgam (Clemmensen Reagent)', category: 'Salts & Reagents', phase: 's', tone: 'from-slate-300 to-slate-400', keywords: ['zn-hg', 'clemmensen'] },
  { id: 'nh2nh2', formula: 'NH2NH2', name: 'Hydrazine (Wolff-Kishner Reagent)', category: 'Salts & Reagents', phase: 'l', tone: 'from-sky-100 to-sky-200', keywords: ['nh2nh2', 'hydrazine', 'wolff-kishner'] },
  { id: 'dry_ether', formula: 'dry_ether', name: 'Dry Ether (Anhydrous Solvent)', category: 'Salts & Reagents', phase: 'l', tone: 'from-sky-50 to-sky-100', keywords: ['ether', 'wurtz solvent', 'grignard'] },
  { id: 'acetone', formula: 'acetone', name: 'Dry Acetone (Finkelstein Solvent)', category: 'Salts & Reagents', phase: 'l', tone: 'from-sky-100 to-sky-200', keywords: ['acetone', 'finkelstein'] },

  // --- Gases ---
  { id: 'co2', formula: 'CO2', name: 'Carbon Dioxide Gas', category: 'Gases', phase: 'g', tone: 'from-slate-200 to-slate-400', keywords: ['co2', 'carbon dioxide', 'gas', 'milky limewater'] },
  { id: 'so2', formula: 'SO2', name: 'Sulphur Dioxide Gas', category: 'Gases', phase: 'g', tone: 'from-yellow-200 to-yellow-400', keywords: ['so2', 'sulphur dioxide', 'gas', 'pungent'] },
  { id: 'h2g', formula: 'H2', name: 'Hydrogen Gas (Pop Sound)', category: 'Gases', phase: 'g', tone: 'from-sky-200 to-blue-400', keywords: ['h2', 'hydrogen', 'gas', 'squeaky pop'] },
  { id: 'cl2g', formula: 'Cl2', name: 'Chlorine Gas', category: 'Gases', phase: 'g', tone: 'from-green-200 to-green-400', keywords: ['cl2', 'chlorine', 'gas', 'greenish'] },
  { id: 'n2', formula: 'N2', name: 'Nitrogen Gas', category: 'Gases', phase: 'g', tone: 'from-teal-200 to-sky-300', keywords: ['n2', 'nitrogen', 'gas'] },
  { id: 'nh3g', formula: 'NH3', name: 'Ammonia Gas', category: 'Gases', phase: 'g', tone: 'from-lime-200 to-lime-300', keywords: ['nh3', 'ammonia', 'gas'] },

  // --- 118 Elements (Anime) ---
  ...ELEMENT_MATERIALS,

  // --- Action Arrows ---
  { id: 'arrow_heat', arrow: 'heat', name: 'Heat Arrow', symbol: 'Δ', category: 'Action Arrows', keywords: ['heat', 'fire', 'temperature', 'delta'] },
  { id: 'arrow_electricity', arrow: 'electricity', name: 'Electricity', symbol: '⚡', category: 'Action Arrows', keywords: ['electricity', 'electrolysis', 'current'] },
  { id: 'arrow_sunlight', arrow: 'sunlight', name: 'Sunlight (hν)', symbol: '☀', category: 'Action Arrows', keywords: ['sunlight', 'light', 'photochemical'] },
  { id: 'arrow_catalyst', arrow: 'catalyst', name: 'Catalyst', symbol: 'cat.', category: 'Action Arrows', keywords: ['catalyst', 'cat'] },
  { id: 'arrow_pressure', arrow: 'pressure', name: 'Pressure', symbol: 'P', category: 'Action Arrows', keywords: ['pressure', 'atm'] },
  { id: 'arrow_hightemp', arrow: 'high_temp', name: 'High Temp', symbol: 'T', category: 'Action Arrows', keywords: ['temperature', 'high temp'] },
];

export function materialById(id) {
  return MATERIAL_CHEMICALS.find((m) => m.id === id);
}

export function materialByFormula(formula) {
  if (!formula) return null;
  const f = formula.trim().toLowerCase();
  return MATERIAL_CHEMICALS.find((m) => m.formula.toLowerCase() === f) || null;
}
