// Master Massive Reactions Database (>2,000 Reactions)
// Features full coverage of:
// 1. Haloalkanes & Haloarenes ("hellowelken") - Finkelstein, Swarts, Wurtz, Wurtz-Fittig, Fittig, Saytzeff, Grignard, Nucleophilic substitutions (SN1, SN2, E1, E2)
// 2. GOC (General Organic Chemistry) - Carbocation rearrangements, carbanions, free radical halogenation, acid-base rankings
// 3. Aldehydes & Ketones - Aldol, Cross-Aldol, Cannizzaro, Clemmensen, Wolff-Kishner, Tollens, Fehling, Iodoform, Stephen
// 4. Benzene & Benzene Diazonium Chloride - Diazotization, Sandmeyer, Gattermann, Balz-Schiemann, Azo Dye couplings (Orange, Yellow, Red)
// 5. Inorganic Qualitative Analysis - Flame tests, Cations Group 0-VI, Brown Ring, Nessler, Chromyl Chloride
// 6. Industrial Syntheses - Haber, Contact, Ostwald, Thermite
// 7. Combinatorial Reaction Engine (Neutralizations, Precipitations, Displacements, Esterifications, Nucleophilic Sub, Carbonate Effervescence) yielding >2,200 total reactions.

export const REACTION_CATEGORIES = [
  'All',
  'Diazonium & Benzene',
  'Aldehydes & Ketones',
  'Haloalkanes & Haloarenes',
  'General Organic Chemistry (GOC)',
  'Qualitative Inorganic Analysis',
  'Industrial & Redox',
  'Acids & Bases (Neutralization)',
  'Precipitation & Salt Matrix',
  'Esterification & Scents',
];

// -------------------------------------------------------------
// 1. Master Curated Organic & Inorganic Named Reactions
// -------------------------------------------------------------
export const CURATED_MASTER_REACTIONS = [
  // --- Benzene & Benzene Diazonium Chloride ---
  {
    id: 'rx_diazotization',
    name: 'Diazotization of Aniline',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5NH2', 'NaNO2', 'HCl'],
    conditions: ['ice_cold', '0_5C'],
    products: ['C6H5N2Cl', 'NaCl', 'H2O'],
    equation: 'C₆H₅NH₂ + NaNO₂ + 2HCl ──(0-5°C)──► C₆H₅N₂⁺Cl⁻ + NaCl + 2H₂O',
    type: 'Diazotization',
    color: '#38bdf8',
    observation: 'clear_yellowish_solution',
    description: 'Aniline reacts with nitrous acid generated in situ at 0-5°C to yield stable Benzene Diazonium Chloride in cold aqueous solution.',
    mechanism: 'Electrophilic attack of nitrosonium ion (NO⁺) on aniline nitrogen followed by tautomerization and dehydration.',
    jeeRelevance: 'Very High (Crucial starting point for aromatic synthesis in JEE/NEET)',
    xp: 250,
  },
  {
    id: 'rx_sandmeyer_cl',
    name: 'Sandmeyer Reaction (Chlorobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuCl', 'HCl'],
    conditions: ['room_temp'],
    products: ['C6H5Cl', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuCl/HCl ──► C₆H₅Cl + N₂↑',
    type: 'Nucleophilic Aromatic Radical Substitution',
    color: '#0284c7',
    observation: 'bubbling',
    description: 'Decomposition of benzene diazonium chloride catalyzed by cuprous chloride yields chlorobenzene with rapid nitrogen gas evolution.',
    mechanism: 'Single-electron transfer from Cu(I) creates aryl radical intermediate which abstracts chlorine.',
    jeeRelevance: 'Top Tier (Standard Sandmeyer halide synthesis)',
    xp: 200,
  },
  {
    id: 'rx_sandmeyer_br',
    name: 'Sandmeyer Reaction (Bromobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuBr', 'HBr'],
    conditions: ['room_temp'],
    products: ['C6H5Br', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuBr/HBr ──► C₆H₅Br + N₂↑',
    type: 'Sandmeyer',
    color: '#d97706',
    observation: 'bubbling',
    description: 'Benzene diazonium chloride reacts with CuBr/HBr to form heavy oily bromobenzene.',
    mechanism: 'Radical substitution via Cu(I) coordination and nitrogen displacement.',
    jeeRelevance: 'High (Direct aromatic bromination)',
    xp: 200,
  },
  {
    id: 'rx_sandmeyer_cn',
    name: 'Sandmeyer Reaction (Benzonitrile)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'CuCN', 'KCN'],
    conditions: ['room_temp'],
    products: ['C6H5CN', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + CuCN/KCN ──► C₆H₅CN + N₂↑',
    type: 'Sandmeyer',
    color: '#64748b',
    observation: 'bubbling',
    description: 'Introduction of cyano group onto benzene ring via cuprous cyanide.',
    mechanism: 'Aryl radical captures cyanide from Cu(I) complex.',
    jeeRelevance: 'High (Key stepping stone to benzoic acid and benzylamine)',
    xp: 220,
  },
  {
    id: 'rx_gattermann_cl',
    name: 'Gattermann Reaction (Chlorobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'Cu', 'HCl'],
    conditions: ['heat'],
    products: ['C6H5Cl', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + Cu powder / HCl ──► C₆H₅Cl + N₂↑',
    type: 'Gattermann Halogenation',
    color: '#0284c7',
    observation: 'bubbling',
    description: 'Modification of Sandmeyer reaction using finely divided copper metal powder instead of cuprous salt.',
    mechanism: 'Heterogeneous electron transfer on copper particle surfaces.',
    jeeRelevance: 'Frequently compared with Sandmeyer reaction in board & competitive exams',
    xp: 180,
  },
  {
    id: 'rx_balz_schiemann',
    name: 'Balz-Schiemann Reaction (Fluorobenzene)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'HBF4'],
    conditions: ['heat'],
    products: ['C6H5F', 'BF3', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + HBF₄ ──► C₆H₅N₂⁺BF₄⁻ ──(Δ)──► C₆H₅F + BF₃↑ + N₂↑',
    type: 'Balz-Schiemann Thermal Fluorination',
    color: '#38bdf8',
    observation: 'white_smoke',
    description: 'Precipitation of insoluble benzene diazonium fluoroborate followed by dry pyrolysis gives pure fluorobenzene.',
    mechanism: 'SN1Ar thermal cleavage through phenyl cation-fluoride ion pair.',
    jeeRelevance: 'Exclusive route to monofluoro aromatic compounds',
    xp: 260,
  },
  {
    id: 'rx_diazonium_iodine',
    name: 'Replacement of Diazonium by Iodine',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'KI'],
    conditions: ['warm'],
    products: ['C6H5I', 'KCl', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + KI ──(warm)──► C₆H₅I + KCl + N₂↑',
    type: 'Nucleophilic Substitution',
    color: '#475569',
    observation: 'bubbling',
    description: 'Simply warming diazonium salt with aqueous potassium iodide yields heavy oily iodobenzene without requiring copper catalyst.',
    mechanism: 'Iodide acts as powerful one-electron reducing agent.',
    jeeRelevance: 'High',
    xp: 190,
  },
  {
    id: 'rx_diazonium_reduction_h3po2',
    name: 'Reduction to Benzene (Hypophosphorous Acid)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'H3PO2', 'H2O'],
    conditions: ['room_temp'],
    products: ['C6H6', 'H3PO3', 'HCl', 'N2'],
    equation: 'C₆H₅N₂⁺Cl⁻ + H₃PO₂ + H₂O ──► C₆H₆ + H₃PO₃ + HCl + N₂↑',
    type: 'Deamination / Reduction',
    color: '#e0f2fe',
    observation: 'bubbling',
    description: 'Complete removal of diazonium group (deamination) regenerating parent benzene.',
    mechanism: 'Hydride transfer from hypophosphorous acid to aryl radical.',
    jeeRelevance: 'Very High (Used for deaminating directing groups in multi-step synthesis)',
    xp: 240,
  },
  {
    id: 'rx_diazonium_hydrolysis',
    name: 'Hydrolysis to Phenol',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'H2O'],
    conditions: ['warm', 'heat'],
    products: ['C6H5OH', 'N2', 'HCl'],
    equation: 'C₆H₅N₂⁺Cl⁻ + H₂O ──(warm 50°C)──► C₆H₅OH + N₂↑ + HCl',
    type: 'Hydrolysis',
    color: '#e2e8f0',
    observation: 'bubbling',
    description: 'Gentle warming of aqueous diazonium solution cleanly hydrolyzes it into phenol.',
    mechanism: 'Aryl cation formation followed by rapid water capture.',
    jeeRelevance: 'High',
    xp: 180,
  },
  {
    id: 'rx_azo_coupling_phenol',
    name: 'Azo Coupling with Phenol (Orange Dye)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'C6H5OH', 'NaOH'],
    conditions: ['ice_cold', 'alkaline_pH9_10'],
    products: ['p_hydroxyazobenzene', 'NaCl', 'H2O'],
    equation: 'C₆H₅N₂⁺Cl⁻ + C₆H₅OH + NaOH ──(pH 9-10)──► p-hydroxyazobenzene (Bright Orange Azo Dye) + NaCl + H₂O',
    type: 'Electrophilic Aromatic Coupling',
    color: '#f97316',
    observation: 'precipitate_orange',
    description: 'In mild alkaline medium (pH 9-10), phenoxide ion attacks diazonium cation at para-position, yielding an intense bright orange azo dye.',
    mechanism: 'Phenoxide anion strongly activates the aromatic ring toward electrophilic attack by the weakly electrophilic diazonium ion.',
    jeeRelevance: 'Top Tier (Hallmark organic qualitative dye test for aniline and phenol)',
    xp: 300,
  },
  {
    id: 'rx_azo_coupling_aniline',
    name: 'Azo Coupling with Aniline (Yellow Butter Dye)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'C6H5NH2'],
    conditions: ['mild_acidic_pH4_5'],
    products: ['p_aminoazobenzene', 'HCl'],
    equation: 'C₆H₅N₂⁺Cl⁻ + C₆H₅NH₂ ──(pH 4-5)──► p-aminoazobenzene (Yellow Dye) + HCl',
    type: 'Electrophilic Aromatic Coupling',
    color: '#facc15',
    observation: 'precipitate_yellow',
    description: 'In mildly acidic conditions (pH 4-5), coupling occurs at the para position of aniline to synthesize yellow dye.',
    mechanism: 'Free amine pair activates the ring; mild acidity prevents diazonium hydroxide formation.',
    jeeRelevance: 'Top Tier (Classic azo dye synthesis)',
    xp: 300,
  },
  {
    id: 'rx_azo_coupling_betanaphthol',
    name: 'Coupling with β-Naphthol (Scarlet Red Dye)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H5N2Cl', 'beta_naphthol', 'NaOH'],
    conditions: ['ice_cold', 'alkaline'],
    products: ['1_phenylazo_2_naphthol', 'NaCl', 'H2O'],
    equation: 'C₆H₅N₂⁺Cl⁻ + β-Naphthol + NaOH ──► 1-phenylazo-2-naphthol (Intense Scarlet Red Precipitate)',
    type: 'Azo Coupling',
    color: '#dc2626',
    observation: 'precipitate_scarlet_red',
    description: 'Azo dye test: Adding cold diazonium solution to alkaline β-naphthol immediately precipitates a brilliant, insoluble scarlet-red dye.',
    mechanism: 'Electrophilic substitution at 1-position of naphthalene nucleus.',
    jeeRelevance: 'Laboratory confirmatory test for primary aromatic amines',
    xp: 320,
  },

  // --- Benzene Electrophilic Aromatic Substitution ---
  {
    id: 'rx_benzene_nitration',
    name: 'Nitration of Benzene',
    category: 'Diazonium & Benzene',
    inputs: ['C6H6', 'HNO3', 'H2SO4'],
    conditions: ['heat_55C'],
    products: ['C6H5NO2', 'H2O'],
    equation: 'C₆H₆ + conc. HNO₃ ──(conc. H₂SO₄, 55°C)──► C₆H₅NO₂ (Nitrobenzene / Oil of Mirbane) + H₂O',
    type: 'Electrophilic Aromatic Substitution (SEAr)',
    color: '#fef08a',
    observation: 'pale_yellow_oil',
    description: 'Nitrating mixture (conc HNO3 + H2SO4) generates the nitronium ion (NO2+) which nitrates benzene to pale yellow nitrobenzene.',
    mechanism: 'Generation of NO₂⁺ by protonation of HNO₃ by H₂SO₄, followed by arenium ion (Wheland intermediate) formation.',
    jeeRelevance: 'Essential JEE Fundamental Reaction',
    xp: 210,
  },
  {
    id: 'rx_benzene_sulphonation',
    name: 'Sulphonation of Benzene',
    category: 'Diazonium & Benzene',
    inputs: ['C6H6', 'fuming_H2SO4'],
    conditions: ['heat'],
    products: ['C6H5SO3H', 'H2O'],
    equation: 'C₆H₆ + SO₃ / H₂SO₄ (Oleum) ──(Δ)──► C₆H₅SO₃H (Benzenesulphonic Acid)',
    type: 'Reversible SEAr',
    color: '#f8fafc',
    observation: 'colorless_solution',
    description: 'Electrophilic attack by neutral sulphur trioxide (SO3) on benzene; completely reversible upon heating with superheated steam.',
    mechanism: 'Neutral electrophile attack followed by proton transfer.',
    jeeRelevance: 'Used extensively as blocking group in organic synthesis',
    xp: 190,
  },
  {
    id: 'rx_benzene_chlorination',
    name: 'Halogenation of Benzene (Chlorination)',
    category: 'Diazonium & Benzene',
    inputs: ['C6H6', 'Cl2', 'FeCl3'],
    conditions: ['room_temp', 'dark'],
    products: ['C6H5Cl', 'HCl'],
    equation: 'C₆H₆ + Cl₂ ──(anhyd. FeCl₃)──► C₆H₅Cl + HCl↑',
    type: 'Electrophilic Halogenation',
    color: '#0284c7',
    observation: 'acidic_vapors',
    description: 'Lewis acid FeCl3 polarizes chlorine into Cl+ equivalent, reacting to form chlorobenzene and white acidic HCl fumes.',
    mechanism: 'FeCl3 + Cl2 -> [FeCl4]- + Cl+; Cl+ attacks benzene ring.',
    jeeRelevance: 'High',
    xp: 190,
  },
  {
    id: 'rx_fc_alkylation',
    name: 'Friedel-Crafts Alkylation',
    category: 'Diazonium & Benzene',
    inputs: ['C6H6', 'CH3Cl', 'AlCl3'],
    conditions: ['anhydrous'],
    products: ['C6H5CH3', 'HCl'],
    equation: 'C₆H₆ + CH₃Cl ──(anhyd. AlCl₃)──► C₆H₅CH₃ (Toluene) + HCl↑',
    type: 'Friedel-Crafts Alkylation',
    color: '#38bdf8',
    observation: 'acidic_vapors',
    description: 'Anhydrous aluminium chloride abstracts chloride to generate methyl carbocation which alkylates the benzene ring to toluene.',
    mechanism: 'Carbocation electrophilic attack; prone to polyalkylation and skeletal rearrangements.',
    jeeRelevance: 'Top Tier (Classic mechanism exam question)',
    xp: 220,
  },
  {
    id: 'rx_fc_acylation',
    name: 'Friedel-Crafts Acylation',
    category: 'Diazonium & Benzene',
    inputs: ['C6H6', 'CH3COCl', 'AlCl3'],
    conditions: ['anhydrous'],
    products: ['C6H5COCH3', 'HCl'],
    equation: 'C₆H₆ + CH₃COCl ──(anhyd. AlCl₃)──► C₆H₅COCH₃ (Acetophenone) + HCl↑',
    type: 'Friedel-Crafts Acylation',
    color: '#94a3b8',
    observation: 'acidic_vapors',
    description: 'Acyl chloride forms resonance-stabilized acylium ion (CH3-C≡O+) with AlCl3, giving acetophenone without rearrangement or polyacylation.',
    mechanism: 'Acylium ion attack; product forms complex with 1 mole AlCl3.',
    jeeRelevance: 'Top Tier (Cleaner synthesis than alkylation)',
    xp: 230,
  },

  // --- Haloalkanes & Haloarenes ("hellowelken") ---
  {
    id: 'rx_finkelstein',
    name: 'Finkelstein Reaction (Halide Exchange)',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['C2H5Cl', 'NaI', 'acetone'],
    conditions: ['reflux'],
    products: ['C2H5I', 'NaCl'],
    equation: 'C₂H₅Cl + NaI ──(dry acetone)──► C₂H₅I + NaCl↓',
    type: 'SN2 Halide Exchange',
    color: '#facc15',
    observation: 'precipitate_white',
    description: 'Driven by Le Chatelier principle: NaCl is insoluble in dry acetone and precipitates, driving equilibrium forward to alkyl iodide.',
    mechanism: 'Concerted SN2 backside attack by nucleophilic iodide on primary haloalkane.',
    jeeRelevance: 'Very High (Named Halide Exchange Reaction)',
    xp: 210,
  },
  {
    id: 'rx_swarts',
    name: 'Swarts Reaction (Alkyl Fluoride Synthesis)',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3Br', 'AgF'],
    conditions: ['heat'],
    products: ['CH3F', 'AgBr'],
    equation: 'CH₃Br + AgF ──(Δ)──► CH₃F + AgBr↓',
    type: 'Halide Exchange',
    color: '#fef08a',
    observation: 'precipitate_cream',
    description: 'Alkyl bromides heated in presence of metallic fluorides (AgF, Hg2F2, SbF3) cleanly yield volatile alkyl fluorides with AgBr precipitate.',
    mechanism: 'Silver ion assists leaving group departure while fluoride attacks carbon.',
    jeeRelevance: 'Very High (Primary method for making alkyl fluorides)',
    xp: 210,
  },
  {
    id: 'rx_wurtz',
    name: 'Wurtz Reaction',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3Cl', 'Na'],
    conditions: ['dry_ether'],
    products: ['C2H6', 'NaCl'],
    equation: '2CH₃Cl + 2Na ──(dry ether)──► C₂H₆ (Ethane) + 2NaCl↓',
    type: 'Reductive Coupling',
    color: '#e2e8f0',
    observation: 'bubbling_effervescence',
    description: 'Two molecules of alkyl halide couple upon treatment with sodium metal in dry ether to form symmetrical higher alkane.',
    mechanism: 'Organosodium intermediate (CH3Na) attacks second molecule of alkyl halide in SN2 fashion.',
    jeeRelevance: 'Top Tier (Symmetrical alkane preparation)',
    xp: 230,
  },
  {
    id: 'rx_wurtz_fittig',
    name: 'Wurtz-Fittig Reaction',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['C6H5Br', 'CH3Br', 'Na'],
    conditions: ['dry_ether'],
    products: ['C6H5CH3', 'NaBr'],
    equation: 'C₆H₅Br + CH₃Br + 2Na ──(dry ether)──► C₆H₅CH₃ (Toluene) + 2NaBr↓',
    type: 'Alkyl-Aryl Coupling',
    color: '#38bdf8',
    observation: 'precipitate_white',
    description: 'Mixture of aryl halide and alkyl halide treated with sodium in dry ether gives alkylarene (toluene).',
    mechanism: 'Aryl carbanion attacks alkyl halide due to superior nucleophilicity.',
    jeeRelevance: 'High',
    xp: 220,
  },
  {
    id: 'rx_fittig',
    name: 'Fittig Reaction',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['C6H5Cl', 'Na'],
    conditions: ['dry_ether', 'heat'],
    products: ['biphenyl', 'NaCl'],
    equation: '2C₆H₅Cl + 2Na ──(dry ether)──► C₆H₅-C₆H₅ (Biphenyl) + 2NaCl↓',
    type: 'Aryl-Aryl Coupling',
    color: '#64748b',
    observation: 'white_crystals',
    description: 'Two molecules of aryl halide couple directly in presence of sodium in dry ether to yield biphenyl.',
    mechanism: 'Radical / organometallic coupling.',
    jeeRelevance: 'High',
    xp: 200,
  },
  {
    id: 'rx_saytzeff_elimination',
    name: "Saytzeff Dehydrohalogenation (E2 Elimination)",
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3CH2CHBrCH3', 'KOH_alc'],
    conditions: ['heat'],
    products: ['but_2_ene', 'KBr', 'H2O'],
    equation: 'CH₃-CH₂-CHBr-CH₃ + alc. KOH ──(Δ)──► CH₃-CH=CH-CH₃ (But-2-ene, 80% Major) + CH₃-CH₂-CH=CH₂ (20% Minor) + KBr + H₂O',
    type: 'E2 Elimination (Saytzeff Rule)',
    color: '#e0f2fe',
    observation: 'effervescence',
    description: "According to Saytzeff's Rule, elimination of β-hydrogen occurs preferentially from β-carbon with fewer hydrogens to give the more substituted, stable alkene.",
    mechanism: 'Concerted anti-periplanar abstraction of proton by ethoxide base with simultaneous halide loss.',
    jeeRelevance: 'Top Tier (Major vs minor product prediction in competitive tests)',
    xp: 250,
  },
  {
    id: 'rx_grignard_prep',
    name: 'Synthesis of Grignard Reagent',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3I', 'Mg'],
    conditions: ['dry_ether', 'anhydrous'],
    products: ['CH3MgI'],
    equation: 'CH₃I + Mg ──(dry ether)──► CH₃MgI (Methylmagnesium Iodide)',
    type: 'Oxidative Insertion',
    color: '#94a3b8',
    observation: 'grey_metal_dissolves',
    description: 'Magnesium metal inserts into the C-halogen bond in dry ether to create the famous organomagnesium Grignard reagent.',
    mechanism: 'Surface single-electron transfer creates radical pair intermediate.',
    jeeRelevance: 'Top Tier (Master carbon-carbon bond builder)',
    xp: 260,
  },
  {
    id: 'rx_grignard_water',
    name: 'Hydrolysis of Grignard Reagent (Alkane Synthesis)',
    category: 'Haloalkanes & Haloarenes',
    inputs: ['CH3MgI', 'H2O'],
    conditions: ['room_temp'],
    products: ['CH4', 'MgOHI'],
    equation: 'CH₃MgI + H₂O ──► CH₄↑ (Methane gas) + Mg(OH)I',
    type: 'Acid-Base Protonation',
    color: '#f0fdf4',
    observation: 'rapid_bubbling_gas',
    description: 'Grignard reagents are powerful bases; any source of acidic proton (water, alcohol, amine) immediately destroys them into hydrocarbons.',
    mechanism: 'Carbanion carbon deprotonates water.',
    jeeRelevance: 'High (Explains why Grignard reactions must be strictly anhydrous)',
    xp: 210,
  },

  // --- Aldehydes & Ketones ---
  {
    id: 'rx_aldol_condensation',
    name: 'Aldol Condensation of Acetaldehyde',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'NaOH_dil'],
    conditions: ['heat'],
    products: ['crotonaldehyde', 'H2O'],
    equation: '2CH₃CHO ──(dil. NaOH)──► [CH₃-CH(OH)-CH₂-CHO] ──(Δ, -H₂O)──► CH₃-CH=CH-CHO (But-2-enal / Crotonaldehyde)',
    type: 'Aldol Condensation',
    color: '#fde047',
    observation: 'pungent_liquid',
    description: 'Aldehydes with α-hydrogen undergo self-addition in presence of dilute base to form β-hydroxyaldehyde (aldol), which dehydrates on heating to α,β-unsaturated aldehyde.',
    mechanism: 'Enolate generation -> nucleophilic attack on carbonyl -> protonation -> E1cB dehydration.',
    jeeRelevance: 'Top Tier (Most tested reaction in JEE/NEET organic chemistry)',
    xp: 320,
  },
  {
    id: 'rx_cross_aldol',
    name: 'Cross-Aldol Condensation (Cinnamaldehyde)',
    category: 'Aldehydes & Ketones',
    inputs: ['C6H5CHO', 'CH3CHO', 'NaOH_dil'],
    conditions: ['room_temp', 'heat'],
    products: ['cinnamaldehyde', 'H2O'],
    equation: 'C₆H₅CHO + CH₃CHO ──(dil. NaOH, Δ)──► C₆H₅-CH=CH-CHO (Cinnamaldehyde, Cinnamon Scent) + H₂O',
    type: 'Cross-Aldol Condensation',
    color: '#eab308',
    observation: 'cinnamon_scent_yellow_oil',
    description: 'Benzaldehyde has no α-hydrogen, so acetaldehyde forms the enolate and attacks benzaldehyde exclusively, yielding fragrant cinnamaldehyde.',
    mechanism: 'Selective nucleophilic attack on aromatic aldehyde followed by dehydration.',
    jeeRelevance: 'Very High',
    xp: 290,
  },
  {
    id: 'rx_cannizzaro',
    name: 'Cannizzaro Reaction (Formaldehyde)',
    category: 'Aldehydes & Ketones',
    inputs: ['HCHO', 'NaOH_conc'],
    conditions: ['room_temp'],
    products: ['CH3OH', 'HCOONa'],
    equation: '2HCHO + conc. NaOH (50%) ──► CH₃OH (Methanol) + HCOONa (Sodium Formate)',
    type: 'Disproportionation / Redox',
    color: '#e2e8f0',
    observation: 'clear_solution',
    description: 'Aldehydes lacking α-hydrogen (HCHO, benzaldehyde) undergo self oxidation-reduction in concentrated alkali: one molecule oxidizes to acid salt, other reduces to alcohol.',
    mechanism: 'Hydride transfer from dianion/monoanion intermediate directly to carbonyl carbon.',
    jeeRelevance: 'Top Tier (Disproportionation archetype)',
    xp: 300,
  },
  {
    id: 'rx_clemmensen',
    name: 'Clemmensen Reduction',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3COCH3', 'Zn_Hg', 'HCl_conc'],
    conditions: ['reflux'],
    products: ['propane', 'H2O', 'ZnCl2'],
    equation: 'CH₃COCH₃ + 4[H] ──(Zn-Hg / conc. HCl, Δ)──► CH₃CH₂CH₃ (Propane) + H₂O',
    type: 'Carbonyl Deoxygenation',
    color: '#0284c7',
    observation: 'bubbling_gas',
    description: 'Amalgamated zinc and concentrated hydrochloric acid reduce aldehyde and ketone carbonyl groups (>C=O) directly into methylene groups (>CH2).',
    mechanism: 'Surface radical reduction on zinc amalgam; suitable for acid-stable substrates.',
    jeeRelevance: 'Top Tier (Tested alongside Wolff-Kishner)',
    xp: 270,
  },
  {
    id: 'rx_wolff_kishner',
    name: 'Wolff-Kishner Reduction',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3COCH3', 'NH2NH2', 'KOH'],
    conditions: ['ethylene_glycol', 'heat_200C'],
    products: ['propane', 'N2', 'H2O'],
    equation: 'CH₃COCH₃ + NH₂NH₂ ──► [Hydrazone] ──(KOH, ethylene glycol, 180-200°C)──► CH₃CH₂CH₃ + N₂↑',
    type: 'Carbonyl Deoxygenation',
    color: '#38bdf8',
    observation: 'vigorous_n2_bubbling',
    description: 'Hydrazone intermediate heated with KOH base in high boiling ethylene glycol loses nitrogen gas, reducing carbonyl group to alkane.',
    mechanism: 'Base deprotonation of hydrazone followed by concerted loss of molecular nitrogen (N2).',
    jeeRelevance: 'Top Tier (Complement to Clemmensen for acid-sensitive substrates)',
    xp: 280,
  },
  {
    id: 'rx_tollens_test',
    name: "Tollens' Test (Silver Mirror Test)",
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'AgNO3', 'NH4OH', 'NaOH'],
    conditions: ['warm_water_bath'],
    products: ['Ag_mirror', 'CH3COONH4', 'NH3', 'H2O'],
    equation: 'CH₃CHO + 2[Ag(NH₃)₂]⁺ + 3OH⁻ ──(warm)──► CH₃COO⁻ + 2Ag↓ (Mirror on Glass Wall) + 4NH₃ + 2H₂O',
    type: 'Qualitative Redox Test for Aldehydes',
    color: '#cbd5e1',
    observation: 'silver_mirror_reflecting',
    description: "Aldehydes readily reduce ammoniacal silver nitrate (Tollens' reagent) to elemental silver which coats the inside of the test tube as a stunning gleaming mirror.",
    mechanism: 'Aldehyde oxidizes to carboxylate while silver(I) diamine complex reduces to metallic silver.',
    jeeRelevance: 'Universal distinction test between aldehydes and ketones',
    xp: 300,
  },
  {
    id: 'rx_fehling_test',
    name: "Fehling's Test (Red Cuprous Oxide)",
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CHO', 'CuSO4', 'NaK_tartrate', 'NaOH'],
    conditions: ['heat'],
    products: ['Cu2O_red', 'CH3COOH', 'H2O'],
    equation: 'R-CHO + 2Cu²⁺ + 5OH⁻ ──(Δ)──► R-COO⁻ + Cu₂O↓ (Bright Red Precipitate) + 3H₂O',
    type: 'Qualitative Redox Test for Aliphatic Aldehydes',
    color: '#dc2626',
    observation: 'precipitate_red_cu2o',
    description: "Aliphatic aldehydes reduce alkaline cupric bistartrate complex into insoluble bright brick-red cuprous oxide (Cu2O) precipitate. Benzaldehyde does not reduce Fehling's.",
    mechanism: 'Two-electron reduction of copper(II) to copper(I) oxide.',
    jeeRelevance: 'High (Distinguishes aliphatic from aromatic aldehydes)',
    xp: 280,
  },
  {
    id: 'rx_iodoform_test',
    name: 'Iodoform / Haloform Test (Acetone)',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3COCH3', 'I2', 'NaOH'],
    conditions: ['warm'],
    products: ['CHI3_yellow', 'CH3COONa', 'NaI', 'H2O'],
    equation: 'CH₃COCH₃ + 3I₂ + 4NaOH ──► CHI₃↓ (Bright Yellow Crystalline Precipitate) + CH₃COONa + 3NaI + 3H₂O',
    type: 'Haloform Cleavage',
    color: '#facc15',
    observation: 'precipitate_iodoform_yellow',
    description: 'Compounds containing CH3-C=O or CH3-CH(OH)- group react with alkaline iodine to form bright yellow crystalline iodoform (CHI3) with characteristic medicinal antiseptic odor.',
    mechanism: 'Progressive iodination of methyl protons followed by nucleophilic hydroxide cleavage of CI3- leaving group.',
    jeeRelevance: 'Top Tier (Diagnostic identification test for methyl ketones and ethanols)',
    xp: 320,
  },
  {
    id: 'rx_stephen_reduction',
    name: 'Stephen Reduction (Nitrile to Aldehyde)',
    category: 'Aldehydes & Ketones',
    inputs: ['CH3CN', 'SnCl2', 'HCl'],
    conditions: ['ether', 'hydrolysis'],
    products: ['CH3CHO', 'NH4Cl', 'SnCl4'],
    equation: 'CH₃-C≡N + SnCl₂ + 2HCl ──► [CH₃-CH=NH·HCl] ──(H₃O⁺, steam)──► CH₃CHO + NH₄Cl',
    type: 'Reduction',
    color: '#38bdf8',
    observation: 'clear_aldehyde_condensate',
    description: 'Nitriles reduced with tin(II) chloride and hydrochloric acid yield aldimine hydrochloride salt, which upon boiling with water yields aldehyde.',
    mechanism: 'Two-electron reduction to imine followed by hydrolytic cleavage.',
    jeeRelevance: 'High (Named reduction of nitriles)',
    xp: 240,
  },

  // --- General Organic Chemistry (GOC) ---
  {
    id: 'rx_goc_phenol_naoh',
    name: 'Acidity Test: Phenol vs Ethanol (Resonance Acidity)',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['C6H5OH', 'NaOH'],
    conditions: ['room_temp'],
    products: ['C6H5ONa', 'H2O'],
    equation: 'C₆H₅OH + NaOH ──► C₆H₅O⁻Na⁺ (Sodium Phenoxide, Soluble) + H₂O',
    type: 'Acid-Base Dissolution',
    color: '#e0f2fe',
    observation: 'cloudy_dissolves_clear',
    description: 'Phenol dissolves readily in dilute aqueous NaOH because phenoxide anion is stabilized by resonance across the aromatic ring. Ethanol does not react with NaOH.',
    mechanism: 'Resonance delocalization of negative charge into ortho and para positions of benzene.',
    jeeRelevance: 'Fundamental GOC concept question in JEE Main & Advanced',
    xp: 220,
  },
  {
    id: 'rx_goc_carboxylic_nahco3',
    name: 'Brisk Effervescence Test (Carboxylic Acid vs Phenol)',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['CH3COOH', 'NaHCO3'],
    conditions: ['room_temp'],
    products: ['CH3COONa', 'CO2', 'H2O'],
    equation: 'CH₃COOH + NaHCO₃ ──► CH₃COONa + CO₂↑ (Brisk Effervescence) + H₂O',
    type: 'Acid Displacement',
    color: '#f8fafc',
    observation: 'brisk_effervescence_bubbles',
    description: 'Carboxylic acids (pKa ~ 4.7) are stronger acids than carbonic acid (pKa ~ 6.4) and liberate vigorous CO2 gas bubbles from NaHCO3. Phenol (pKa ~ 10) fails this test.',
    mechanism: 'Proton transfer creates H2CO3 which spontaneously decomposes to H2O and CO2 gas.',
    jeeRelevance: 'Standard functional group distinction test',
    xp: 230,
  },
  {
    id: 'rx_goc_free_radical_bromination',
    name: 'Regioselective Free Radical Bromination (3° Carbon)',
    category: 'General Organic Chemistry (GOC)',
    inputs: ['isobutane', 'Br2'],
    conditions: ['sunlight_hv', '127C'],
    products: ['tert_butyl_bromide', 'HBr'],
    equation: '(CH₃)₃CH + Br₂ ──(hν, 127°C)──► (CH₃)₃C-Br (99% Regioselectivity) + HBr↑',
    type: 'Free Radical Halogenation',
    color: '#ea580c',
    observation: 'brown_color_discharges',
    description: 'Bromine radicals exhibit 1600:1 selectivity for tertiary C-H bonds due to hyperconjugation and stability of 3° free radicals (Hammond postulate).',
    mechanism: 'Chain initiation, propagation via tertiary radical, termination.',
    jeeRelevance: 'High (Core free radical selectivity concept)',
    xp: 250,
  },

  // --- Qualitative Inorganic Analysis & Flame Tests ---
  {
    id: 'rx_flame_sodium',
    name: 'Flame Test: Sodium (D-Line Golden Yellow)',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NaCl', 'Bunsen_Flame'],
    conditions: ['high_temp', 'blue_roaring_flame'],
    products: ['Na_excited'],
    equation: 'Na⁺(aq) + e⁻ ──(Bunsen Flame 1200°C)──► Na*(3p) ──► Na(3s) + hν (589 nm D-Lines)',
    type: 'Atomic Emission Spectroscopy',
    color: '#facc15',
    observation: 'blinding_golden_yellow_flame',
    description: 'Sodium imparts an overwhelming, persistent brilliant golden-yellow color to the non-luminous Bunsen flame.',
    mechanism: 'Thermal excitation of 3s valence electron to 3p level followed by photon emission at 589.0 nm.',
    jeeRelevance: 'Universal qualitative analysis test',
    xp: 180,
  },
  {
    id: 'rx_flame_potassium',
    name: 'Flame Test: Potassium (Lilac Flame)',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['KCl', 'Bunsen_Flame'],
    conditions: ['high_temp'],
    products: ['K_excited'],
    equation: 'K⁺ ──(Flame)──► Lilac / Violet Flame (Viewed through Cobalt Blue Glass)',
    type: 'Flame Emission',
    color: '#0ea5e9',
    observation: 'lilac_flame',
    description: 'Potassium salts color the Bunsen flame pale violet/lilac, masked by sodium impurities unless viewed through blue cobalt glass.',
    mechanism: 'Excitation of 4s electron emitting at 766 nm and 404 nm.',
    jeeRelevance: 'High',
    xp: 180,
  },
  {
    id: 'rx_flame_calcium',
    name: 'Flame Test: Calcium (Brick Red)',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['CaCl2', 'Bunsen_Flame'],
    conditions: ['high_temp'],
    products: ['Ca_excited'],
    equation: 'Ca²⁺ ──(Flame)──► Characteristic Brick-Red Flame',
    type: 'Flame Emission',
    color: '#f97316',
    observation: 'brick_red_flame',
    description: 'Calcium volatilizes in the flame to produce a transient flash of brick-red luminescence.',
    mechanism: 'CaOH and Ca+ molecular/atomic band transitions in the flame.',
    jeeRelevance: 'High',
    xp: 180,
  },
  {
    id: 'rx_flame_barium',
    name: 'Flame Test: Barium (Apple Green)',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['BaCl2', 'Bunsen_Flame'],
    conditions: ['high_temp'],
    products: ['Ba_excited'],
    equation: 'Ba²⁺ ──(Flame)──► Persistent Grassy Apple-Green Flame',
    type: 'Flame Emission',
    color: '#84cc16',
    observation: 'apple_green_flame',
    description: 'Barium chloride moistened with conc HCl gives an unmistakable, persistent apple-green coloration to the flame.',
    mechanism: 'BaCl and BaOH molecular band emissions at 510-530 nm.',
    jeeRelevance: 'High',
    xp: 180,
  },
  {
    id: 'rx_brown_ring',
    name: 'Brown Ring Test for Nitrates',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['KNO3', 'FeSO4', 'H2SO4_conc'],
    conditions: ['carefully_layered', 'cold'],
    products: ['Fe_H2O_5_NO_SO4', 'H2O'],
    equation: 'NO₃⁻ + 3Fe²⁺ + 4H⁺ ──► NO + 3Fe³⁺ + 2H₂O;  [Fe(H₂O)₆]²⁺ + NO ──► [Fe(H₂O)₅(NO)]²⁺ (Dark Brown Ring)',
    type: 'Coordination Complex Formation',
    color: '#78350f',
    observation: 'brown_ring_at_junction',
    description: 'Concentrated sulphuric acid poured down the side of the tube forms a separate bottom layer; a magnificent dark brown ring forms at the liquid junction.',
    mechanism: 'Nitric oxide binds to pentaaquairon(II) with charge transfer: Fe(I)-NO⁺ formulation.',
    jeeRelevance: 'Top Tier (Classic laboratory confirmation for nitrate ion)',
    xp: 320,
  },
  {
    id: 'rx_nessler_ammonium',
    name: "Nessler's Reagent Test for Ammonium Ion (Group 0)",
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NH4Cl', 'K2HgI4', 'KOH'],
    conditions: ['alkaline'],
    products: ['iodide_of_millon_base', 'KI', 'H2O'],
    equation: '2[HgI₄]²⁻ + NH₄⁺ + 4OH⁻ ──► H₂N-Hg-O-Hg-I↓ (Iodide of Millon\'s Base, Brown Precipitate) + 7I⁻ + 3H₂O',
    type: 'Precipitation Complexation',
    color: '#9a3412',
    observation: 'brown_precipitate_millon',
    description: 'Addition of alkaline potassium tetraiodomercurate(II) (Nessler\'s reagent) to ammonium salt produces a distinctive brown precipitate.',
    mechanism: 'Nucleophilic attack of ammonia on mercuric iodide complex creating bridging oxo-mercuric network.',
    jeeRelevance: 'Top Tier (Group 0 cation confirmatory test)',
    xp: 310,
  },
  {
    id: 'rx_chromyl_chloride',
    name: 'Chromyl Chloride Test for Chloride Ions',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NaCl', 'K2Cr2O7', 'H2SO4_conc'],
    conditions: ['heat'],
    products: ['CrO2Cl2', 'KHSO4', 'NaHSO4', 'H2O'],
    equation: 'K₂Cr₂O₇ + 4NaCl + 6H₂SO₄ ──(Δ)──► 2CrO₂Cl₂↑ (Deep Red Chromyl Chloride Vapors) + 2KHSO₄ + 4NaHSO₄ + 3H₂O',
    type: 'Acid Oxidation Volatilization',
    color: '#dc2626',
    observation: 'red_vapors_yellow_lead_chromate',
    description: 'Heating chloride salt with solid potassium dichromate and conc sulphuric acid produces volatile deep red chromyl chloride vapors; absorbed in NaOH gives yellow solution.',
    mechanism: 'Generation of chlorochromic acid which condenses to gaseous volatile chromyl chloride.',
    jeeRelevance: 'Top Tier (Does not respond for covalent chlorides like HgCl2, AgCl, PbCl2)',
    xp: 340,
  },
  {
    id: 'rx_fe_nh4oh',
    name: 'Group III Cation Test: Iron(III) with Ammonium Hydroxide',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['FeCl3', 'NH4OH', 'NH4Cl'],
    conditions: ['room_temp'],
    products: ['Fe_OH_3', 'NH4Cl'],
    equation: 'Fe³⁺ + 3NH₄OH ──(NH₄Cl buffer)──► Fe(OH)₃↓ (Reddish-Brown Gelatinous Precipitate) + 3NH₄⁺',
    type: 'Group III Hydroxide Precipitation',
    color: '#991b1b',
    observation: 'gelatinous_reddish_brown_ppt',
    description: 'In presence of NH4Cl common ion buffer, ferric iron precipitates as thick gelatinous reddish-brown iron(III) hydroxide.',
    mechanism: 'Common ion effect suppresses OH- concentration just enough to exceed Ksp of Fe(OH)3 but keep Group IV in solution.',
    jeeRelevance: 'High',
    xp: 200,
  },
  {
    id: 'rx_cu_h2s',
    name: 'Group II Cation Test: Copper(II) with Hydrogen Sulphide',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['CuSO4', 'H2S', 'HCl_dil'],
    conditions: ['acidic_medium'],
    products: ['CuS', 'H2SO4'],
    equation: 'Cu²⁺ + H₂S ──(dil. HCl, pH < 2)──► CuS↓ (Insoluble Jet Black Precipitate) + 2H⁺',
    type: 'Group II Sulphide Precipitation',
    color: '#0f172a',
    observation: 'jet_black_precipitate',
    description: 'Passing H2S gas through acidic solution precipitates copper as pitch-black copper(II) sulphide due to its extremely low solubility product (Ksp ~ 6 x 10^-36).',
    mechanism: 'Low sulfide ion concentration in acidic HCl is sufficient only for Group II precipitation.',
    jeeRelevance: 'High',
    xp: 220,
  },
  {
    id: 'rx_ni_dmg',
    name: 'Nickel Confirmatory: Dimethylglyoxime (DMG) Test',
    category: 'Qualitative Inorganic Analysis',
    inputs: ['NiCl2', 'DMG', 'NH4OH'],
    conditions: ['mild_ammoniacal'],
    products: ['Ni_DMG_2', 'NH4Cl', 'H2O'],
    equation: 'Ni²⁺ + 2(DMG) + 2NH₄OH ──► [Ni(DMG)₂]↓ (Brilliant Rosy Scarlet Red Chelate) + 2NH₄⁺ + 2H₂O',
    type: 'Chelate Coordination Precipitation',
    color: '#e11d48',
    observation: 'brilliant_scarlet_red_ppt',
    description: 'Addition of ethanolic dimethylglyoxime to an ammoniacal nickel solution yields a voluminous, radiant scarlet-red square planar complex stabilized by intramolecular hydrogen bonds.',
    mechanism: 'Intramolecular O-H···O hydrogen bonding locks square planar Ni(II) low-spin d8 complex.',
    jeeRelevance: 'Top Tier (One of the most famous coordination tests)',
    xp: 320,
  },

  // --- Industrial & Redox Processes ---
  {
    id: 'rx_haber_process',
    name: 'Haber-Bosch Ammonia Synthesis',
    category: 'Industrial & Redox',
    inputs: ['N2', 'H2'],
    conditions: ['Fe_catalyst', 'Mo_promoter', 'heat_450C', 'pressure_200atm'],
    products: ['NH3'],
    equation: 'N₂ + 3H₂ ⇌ 2NH₃  (ΔH = -92.4 kJ/mol, 450°C, 200 atm, Fe/Mo)',
    type: 'Exothermic Equilibrium Synthesis',
    color: '#38bdf8',
    observation: 'ammonia_gas_smell',
    description: 'Industrial synthesis of ammonia from atmospheric nitrogen and hydrogen gas using finely divided iron catalyst with molybdenum promoter at 200 atm pressure.',
    mechanism: 'Dissociative adsorption of nitrogen molecules on iron crystal step sites is the rate-determining step.',
    jeeRelevance: 'Very High (Classic Le Chatelier and industrial conditions problem)',
    xp: 250,
  },
  {
    id: 'rx_contact_process',
    name: 'Contact Process (Sulphuric Acid Synthesis)',
    category: 'Industrial & Redox',
    inputs: ['SO2', 'O2'],
    conditions: ['V2O5_catalyst', 'heat_450C', 'pressure_2atm'],
    products: ['SO3'],
    equation: '2SO₂ + O₂ ⇌ 2SO₃ (V₂O₅ catalyst, 450°C, 2 atm) ──► Oleum ──► H₂SO₄',
    type: 'Catalytic Oxidation',
    color: '#eab308',
    observation: 'dense_white_fumes_so3',
    description: 'Oxidation of sulfur dioxide to sulfur trioxide over vanadium pentoxide (V2O5) catalyst; absorbed in H2SO4 to form oleum (H2S2O7).',
    mechanism: 'Vanadium cycles between V(V) and V(IV) oxidation states during catalytic turnover.',
    jeeRelevance: 'High',
    xp: 240,
  },
  {
    id: 'rx_ostwald_process',
    name: 'Ostwald Process (Nitric Acid Synthesis)',
    category: 'Industrial & Redox',
    inputs: ['NH3', 'O2'],
    conditions: ['Pt_Rh_gauze', 'heat_800C'],
    products: ['NO', 'H2O'],
    equation: '4NH₃ + 5O₂ ──(Pt/Rh gauze, 800°C)──► 4NO + 6H₂O;  2NO + O₂ ──► 2NO₂ ──► HNO₃',
    type: 'Catalytic Ammonia Oxidation',
    color: '#f97316',
    observation: 'reddish_brown_no2_fumes',
    description: 'Ammonia is catalytically burned over platinum-rhodium gauze at 800°C to nitric oxide, oxidized to NO2, and absorbed in water to yield nitric acid.',
    mechanism: 'Rapid surface oxidation on noble metal wire gauze.',
    jeeRelevance: 'High',
    xp: 240,
  },
  {
    id: 'rx_thermite',
    name: 'Goldschmidt Thermite Reaction',
    category: 'Industrial & Redox',
    inputs: ['Fe2O3', 'Al'],
    conditions: ['Mg_ribbon_fuse', 'spark'],
    products: ['Al2O3', 'Fe_molten'],
    equation: 'Fe₂O₃ + 2Al ──(Ignition)──► Al₂O₃ + 2Fe (Liquid Molten Iron ~2500°C) + 851.5 kJ',
    type: 'Violent Exothermic Redox',
    color: '#f59e0b',
    observation: 'white_hot_sparks_molten_iron',
    description: 'Aluminium reduces iron(III) oxide with ferocious exothermicity, reaching temperatures high enough to yield white-hot molten iron used for in-situ rail welding.',
    mechanism: 'Extreme affinity of aluminium for oxygen due to tremendous crystal lattice energy of Al2O3.',
    jeeRelevance: 'High',
    xp: 350,
  },
];

// -------------------------------------------------------------
// 2. Combinatorial Reaction Generator Engine (>2,100 Reactions)
// -------------------------------------------------------------
export function generateAllReactions() {
  const generated = [];

  // A. Comprehensive Acid-Base Neutralization Matrix (45 Acids x 30 Bases = 1,350 reactions)
  const ACIDS = [
    { formula: 'HCl', name: 'Hydrochloric Acid', anion: 'Cl', anionName: 'Chloride', val: 1 },
    { formula: 'HBr', name: 'Hydrobromic Acid', anion: 'Br', anionName: 'Bromide', val: 1 },
    { formula: 'HI', name: 'Hydroiodic Acid', anion: 'I', anionName: 'Iodide', val: 1 },
    { formula: 'HNO3', name: 'Nitric Acid', anion: 'NO3', anionName: 'Nitrate', val: 1 },
    { formula: 'H2SO4', name: 'Sulphuric Acid', anion: 'SO4', anionName: 'Sulphate', val: 2 },
    { formula: 'H3PO4', name: 'Phosphoric Acid', anion: 'PO4', anionName: 'Phosphate', val: 3 },
    { formula: 'CH3COOH', name: 'Acetic Acid', anion: 'CH3COO', anionName: 'Acetate', val: 1 },
    { formula: 'HCOOH', name: 'Formic Acid', anion: 'HCOO', anionName: 'Formate', val: 1 },
    { formula: 'H2C2O4', name: 'Oxalic Acid', anion: 'C2O4', anionName: 'Oxalate', val: 2 },
    { formula: 'HClO4', name: 'Perchloric Acid', anion: 'ClO4', anionName: 'Perchlorate', val: 1 },
    { formula: 'H2SO3', name: 'Sulphurous Acid', anion: 'SO3', anionName: 'Sulphite', val: 2 },
    { formula: 'HNO2', name: 'Nitrous Acid', anion: 'NO2', anionName: 'Nitrite', val: 1 },
    { formula: 'HF', name: 'Hydrofluoric Acid', anion: 'F', anionName: 'Fluoride', val: 1 },
    { formula: 'HCN', name: 'Hydrocyanic Acid', anion: 'CN', anionName: 'Cyanide', val: 1 },
    { formula: 'C6H5COOH', name: 'Benzoic Acid', anion: 'C6H5COO', anionName: 'Benzoate', val: 1 },
    { formula: 'H2CO3', name: 'Carbonic Acid', anion: 'CO3', anionName: 'Carbonate', val: 2 },
    { formula: 'H3BO3', name: 'Boric Acid', anion: 'BO3', anionName: 'Borate', val: 3 },
    { formula: 'C2H5COOH', name: 'Propionic Acid', anion: 'C2H5COO', anionName: 'Propionate', val: 1 },
    { formula: 'C3H7COOH', name: 'Butyric Acid', anion: 'C3H7COO', anionName: 'Butyrate', val: 1 },
    { formula: 'C6H8O7', name: 'Citric Acid', anion: 'C6H5O7', anionName: 'Citrate', val: 3 },
    { formula: 'H2S', name: 'Hydrosulphuric Acid', anion: 'S', anionName: 'Sulphide', val: 2 },
    { formula: 'HIO3', name: 'Iodic Acid', anion: 'IO3', anionName: 'Iodate', val: 1 },
    { formula: 'HBrO3', name: 'Bromic Acid', anion: 'BrO3', anionName: 'Bromate', val: 1 },
    { formula: 'HClO3', name: 'Chloric Acid', anion: 'ClO3', anionName: 'Chlorate', val: 1 },
    { formula: 'H2CrO4', name: 'Chromic Acid', anion: 'CrO4', anionName: 'Chromate', val: 2 },
    { formula: 'H2Cr2O7', name: 'Dichromic Acid', anion: 'Cr2O7', anionName: 'Dichromate', val: 2 },
    { formula: 'HMnO4', name: 'Permanganic Acid', anion: 'MnO4', anionName: 'Permanganate', val: 1 },
    { formula: 'H3PO3', name: 'Phosphorous Acid', anion: 'HPO3', anionName: 'Phosphite', val: 2 },
    { formula: 'H3PO2', name: 'Hypophosphorous Acid', anion: 'H2PO2', anionName: 'Hypophosphite', val: 1 },
    { formula: 'HSCN', name: 'Thiocyanic Acid', anion: 'SCN', anionName: 'Thiocyanate', val: 1 },
    { formula: 'C4H6O6', name: 'Tartaric Acid', anion: 'C4H4O6', anionName: 'Tartrate', val: 2 },
    { formula: 'C3H6O3', name: 'Lactic Acid', anion: 'C3H5O3', anionName: 'Lactate', val: 1 },
    { formula: 'C7H6O3', name: 'Salicylic Acid', anion: 'C7H5O3', anionName: 'Salicylate', val: 1 },
    { formula: 'C8H6O4', name: 'Phthalic Acid', anion: 'C8H4O4', anionName: 'Phthalate', val: 2 },
    { formula: 'C4H4O4', name: 'Maleic Acid', anion: 'C4H2O4', anionName: 'Maleate', val: 2 },
    { formula: 'C4H4O4_fum', name: 'Fumaric Acid', anion: 'C4H2O4', anionName: 'Fumarate', val: 2 },
    { formula: 'C3H4O4', name: 'Malonic Acid', anion: 'C3H2O4', anionName: 'Malonate', val: 2 },
    { formula: 'C4H6O4', name: 'Succinic Acid', anion: 'C4H4O4', anionName: 'Succinate', val: 2 },
    { formula: 'C5H8O4', name: 'Glutaric Acid', anion: 'C5H6O4', anionName: 'Glutarate', val: 2 },
    { formula: 'C6H10O4', name: 'Adipic Acid', anion: 'C6H8O4', anionName: 'Adipate', val: 2 },
    { formula: 'H2SeO4', name: 'Selenic Acid', anion: 'SeO4', anionName: 'Selenate', val: 2 },
    { formula: 'H2TeO4', name: 'Telluric Acid', anion: 'TeO4', anionName: 'Tellurate', val: 2 },
    { formula: 'H4SiO4', name: 'Orthosilicic Acid', anion: 'SiO4', anionName: 'Silicate', val: 4 },
    { formula: 'HOCN', name: 'Cyanic Acid', anion: 'OCN', anionName: 'Cyanate', val: 1 },
    { formula: 'HN3', name: 'Hydrazoic Acid', anion: 'N3', anionName: 'Azide', val: 1 },
  ];

  const BASES = [
    { formula: 'NaOH', name: 'Sodium Hydroxide', cation: 'Na', cationName: 'Sodium', val: 1 },
    { formula: 'KOH', name: 'Potassium Hydroxide', cation: 'K', cationName: 'Potassium', val: 1 },
    { formula: 'LiOH', name: 'Lithium Hydroxide', cation: 'Li', cationName: 'Lithium', val: 1 },
    { formula: 'CsOH', name: 'Caesium Hydroxide', cation: 'Cs', cationName: 'Caesium', val: 1 },
    { formula: 'RbOH', name: 'Rubidium Hydroxide', cation: 'Rb', cationName: 'Rubidium', val: 1 },
    { formula: 'Ca(OH)2', name: 'Calcium Hydroxide', cation: 'Ca', cationName: 'Calcium', val: 2 },
    { formula: 'Ba(OH)2', name: 'Barium Hydroxide', cation: 'Ba', cationName: 'Barium', val: 2 },
    { formula: 'Sr(OH)2', name: 'Strontium Hydroxide', cation: 'Sr', cationName: 'Strontium', val: 2 },
    { formula: 'Mg(OH)2', name: 'Magnesium Hydroxide', cation: 'Mg', cationName: 'Magnesium', val: 2 },
    { formula: 'NH4OH', name: 'Ammonium Hydroxide', cation: 'NH4', cationName: 'Ammonium', val: 1 },
    { formula: 'Al(OH)3', name: 'Aluminium Hydroxide', cation: 'Al', cationName: 'Aluminium', val: 3 },
    { formula: 'Zn(OH)2', name: 'Zinc Hydroxide', cation: 'Zn', cationName: 'Zinc', val: 2 },
    { formula: 'Fe(OH)3', name: 'Iron(III) Hydroxide', cation: 'Fe', cationName: 'Iron(III)', val: 3 },
    { formula: 'Fe(OH)2', name: 'Iron(II) Hydroxide', cation: 'Fe', cationName: 'Iron(II)', val: 2 },
    { formula: 'Cu(OH)2', name: 'Copper(II) Hydroxide', cation: 'Cu', cationName: 'Copper(II)', val: 2 },
    { formula: 'Ni(OH)2', name: 'Nickel Hydroxide', cation: 'Ni', cationName: 'Nickel', val: 2 },
    { formula: 'Co(OH)2', name: 'Cobalt(II) Hydroxide', cation: 'Co', cationName: 'Cobalt(II)', val: 2 },
    { formula: 'Mn(OH)2', name: 'Manganese(II) Hydroxide', cation: 'Mn', cationName: 'Manganese(II)', val: 2 },
    { formula: 'Cr(OH)3', name: 'Chromium(III) Hydroxide', cation: 'Cr', cationName: 'Chromium(III)', val: 3 },
    { formula: 'AgOH', name: 'Silver Hydroxide', cation: 'Ag', cationName: 'Silver', val: 1 },
    { formula: 'Pb(OH)2', name: 'Lead(II) Hydroxide', cation: 'Pb', cationName: 'Lead(II)', val: 2 },
    { formula: 'Bi(OH)3', name: 'Bismuth Hydroxide', cation: 'Bi', cationName: 'Bismuth', val: 3 },
    { formula: 'Cd(OH)2', name: 'Cadmium Hydroxide', cation: 'Cd', cationName: 'Cadmium', val: 2 },
    { formula: 'Sn(OH)2', name: 'Tin(II) Hydroxide', cation: 'Sn', cationName: 'Tin(II)', val: 2 },
    { formula: 'Sn(OH)4', name: 'Tin(IV) Hydroxide', cation: 'Sn', cationName: 'Tin(IV)', val: 4 },
    { formula: 'La(OH)3', name: 'Lanthanum Hydroxide', cation: 'La', cationName: 'Lanthanum', val: 3 },
    { formula: 'Ce(OH)3', name: 'Cerium(III) Hydroxide', cation: 'Ce', cationName: 'Cerium', val: 3 },
    { formula: 'Y(OH)3', name: 'Yttrium Hydroxide', cation: 'Y', cationName: 'Yttrium', val: 3 },
    { formula: 'Sc(OH)3', name: 'Scandium Hydroxide', cation: 'Sc', cationName: 'Scandium', val: 3 },
    { formula: 'Zr(OH)4', name: 'Zirconium Hydroxide', cation: 'Zr', cationName: 'Zirconium', val: 4 },
  ];

  ACIDS.forEach((acid, aIdx) => {
    BASES.forEach((base, bIdx) => {
      const saltFormula = formatSalt(base.cation, base.val, acid.anion, acid.val);
      const saltName = `${base.cationName} ${acid.anionName}`;
      generated.push({
        id: `rx_neut_${aIdx}_${bIdx}`,
        name: `Neutralization: ${acid.name} + ${base.name}`,
        category: 'Acids & Bases (Neutralization)',
        inputs: [acid.formula, base.formula],
        conditions: ['aqueous'],
        products: [saltFormula, 'H2O'],
        equation: `${acid.formula} + ${base.formula} ──► ${saltFormula} + H₂O (ΔH ≈ -57.1 kJ/mol)`,
        type: 'Acid-Base Neutralization',
        color: '#e0f2fe',
        observation: 'mild_warming_colorless',
        description: `Exothermic neutralization between ${acid.name} and ${base.name} producing ${saltName} and water.`,
        mechanism: 'H⁺(aq) + OH⁻(aq) ──► H₂O(l)',
        jeeRelevance: 'Standard enthalpy of neutralization concept',
        xp: 75,
      });
    });
  });

  // B. Haloalkanes & Haloarenes Nucleophilic Substitution Matrix (20 Halides x 15 Nucleophiles = 300 reactions)
  const ALKYL_HALIDES = [
    { formula: 'CH3Cl', name: 'Chloromethane (Methyl Chloride)', rGroup: 'CH3' },
    { formula: 'CH3Br', name: 'Bromomethane (Methyl Bromide)', rGroup: 'CH3' },
    { formula: 'CH3I', name: 'Iodomethane (Methyl Iodide)', rGroup: 'CH3' },
    { formula: 'C2H5Cl', name: 'Chloroethane (Ethyl Chloride)', rGroup: 'C2H5' },
    { formula: 'C2H5Br', name: 'Bromoethane (Ethyl Bromide)', rGroup: 'C2H5' },
    { formula: 'C2H5I', name: 'Iodoethane (Ethyl Iodide)', rGroup: 'C2H5' },
    { formula: 'C3H7Cl', name: '1-Chloropropane (n-Propyl Chloride)', rGroup: 'C3H7' },
    { formula: 'C3H7Br', name: '1-Bromopropane (n-Propyl Bromide)', rGroup: 'C3H7' },
    { formula: 'C3H7I', name: '1-Iodopropane (n-Propyl Iodide)', rGroup: 'C3H7' },
    { formula: 'CH3CHBrCH3', name: '2-Bromopropane (Isopropyl Bromide)', rGroup: 'CH(CH3)2' },
    { formula: 'CH3CHICH3', name: '2-Iodopropane (Isopropyl Iodide)', rGroup: 'CH(CH3)2' },
    { formula: 'C4H9Cl', name: '1-Chlorobutane (n-Butyl Chloride)', rGroup: 'C4H9' },
    { formula: 'C4H9Br', name: '1-Bromobutane (n-Butyl Bromide)', rGroup: 'C4H9' },
    { formula: '(CH3)3CCl', name: 'tert-Butyl Chloride', rGroup: 'C(CH3)3' },
    { formula: '(CH3)3CBr', name: 'tert-Butyl Bromide', rGroup: 'C(CH3)3' },
    { formula: 'CH2=CHCH2Cl', name: 'Allyl Chloride', rGroup: 'CH2=CHCH2' },
    { formula: 'CH2=CHCH2Br', name: 'Allyl Bromide', rGroup: 'CH2=CHCH2' },
    { formula: 'C6H5CH2Cl', name: 'Benzyl Chloride', rGroup: 'C6H5CH2' },
    { formula: 'C6H5CH2Br', name: 'Benzyl Bromide', rGroup: 'C6H5CH2' },
    { formula: 'C6H5Cl', name: 'Chlorobenzene', rGroup: 'C6H5' },
  ];

  const NUCLEOPHILES = [
    { reagent: 'KOH_aq', nucName: 'Aqueous Hydroxide', productFn: (r) => `${r}-OH`, pName: 'Alcohol', mech: 'SN2 / SN1' },
    { reagent: 'KCN', nucName: 'Potassium Cyanide', productFn: (r) => `${r}-CN`, pName: 'Alkyl Nitrile', mech: 'Ambident Nucleophile C-Attack' },
    { reagent: 'AgCN', nucName: 'Silver Cyanide', productFn: (r) => `${r}-NC`, pName: 'Alkyl Isocyanide (Carbylamine)', mech: 'Covalent Ag Coordination N-Attack' },
    { reagent: 'KNO2', nucName: 'Potassium Nitrite', productFn: (r) => `${r}-O-N=O`, pName: 'Alkyl Nitrite', mech: 'Ambident O-Attack' },
    { reagent: 'AgNO2', nucName: 'Silver Nitrite', productFn: (r) => `${r}-NO2`, pName: 'Nitroalkane', mech: 'Ambident N-Attack' },
    { reagent: 'NH3', nucName: 'Ammonia', productFn: (r) => `${r}-NH2`, pName: 'Primary Amine', mech: 'Hoffmann Ammonolysis' },
    { reagent: 'CH3NH2', nucName: 'Methylamine', productFn: (r) => `${r}-NHCH3`, pName: 'Secondary Amine', mech: 'Nucleophilic Substitution' },
    { reagent: 'CH3COONa', nucName: 'Sodium Acetate', productFn: (r) => `CH3COO-${r}`, pName: 'Acetate Ester', mech: 'Carboxylate Nucleophile' },
    { reagent: 'NaSH', nucName: 'Sodium Hydrosulphide', productFn: (r) => `${r}-SH`, pName: 'Thiol (Mercaptan)', mech: 'Thiolate Substitution' },
    { reagent: 'NaOCH3', nucName: 'Sodium Methoxide', productFn: (r) => `${r}-O-CH3`, pName: 'Methyl Ether', mech: 'Williamson Ether Synthesis' },
    { reagent: 'NaOC2H5', nucName: 'Sodium Ethoxide', productFn: (r) => `${r}-O-C2H5`, pName: 'Ethyl Ether', mech: 'Williamson Ether Synthesis' },
    { reagent: 'NaN3', nucName: 'Sodium Azide', productFn: (r) => `${r}-N3`, pName: 'Alkyl Azide', mech: 'Azide Substitution' },
    { reagent: 'NaI', nucName: 'Sodium Iodide', productFn: (r) => `${r}-I`, pName: 'Alkyl Iodide', mech: 'Finkelstein SN2 Halide Exchange' },
    { reagent: 'NaSCN', nucName: 'Sodium Thiocyanate', productFn: (r) => `${r}-SCN`, pName: 'Alkyl Thiocyanate', mech: 'Thiocyanate Attack' },
    { reagent: 'C6H5ONa', nucName: 'Sodium Phenoxide', productFn: (r) => `C6H5-O-${r}`, pName: 'Aryl Alkyl Ether', mech: 'Phenoxide Alkylation' },
  ];

  ALKYL_HALIDES.forEach((rxSub, sIdx) => {
    NUCLEOPHILES.forEach((nuc, nIdx) => {
      const prod = nuc.productFn(rxSub.rGroup);
      generated.push({
        id: `rx_nuc_sub_${sIdx}_${nIdx}`,
        name: `Nucleophilic Substitution: ${rxSub.name} + ${nuc.nucName}`,
        category: 'Haloalkanes & Haloarenes',
        inputs: [rxSub.formula, nuc.reagent],
        conditions: ['reflux'],
        products: [prod, 'Halide_Salt'],
        equation: `${rxSub.formula} + ${nuc.reagent} ──► ${prod} (${nuc.pName}) + Salt`,
        type: `Nucleophilic Substitution (${nuc.mech})`,
        color: '#38bdf8',
        observation: 'colorless_liquid_layer',
        description: `Displacement of halogen in ${rxSub.name} by ${nuc.nucName} to yield ${nuc.pName}.`,
        mechanism: `${nuc.mech}: Nucleophilic attack on electrophilic carbon.`,
        jeeRelevance: 'Core Haloalkanes JEE/NEET syllabus topic',
        xp: 130,
      });
    });
  });

  // C. Precipitation Matrix (Cations x Anions)
  const PRECIP_PAIRS = [
    { cation: 'AgNO3', catName: 'Silver', anion: 'NaCl', anName: 'Chloride', ppt: 'AgCl', color: '#ffffff', obs: 'precipitate_white_curdy', name: 'Silver Chloride' },
    { cation: 'AgNO3', catName: 'Silver', anion: 'NaBr', anName: 'Bromide', ppt: 'AgBr', color: '#fef08a', obs: 'precipitate_pale_yellow', name: 'Silver Bromide' },
    { cation: 'AgNO3', catName: 'Silver', anion: 'KI', anName: 'Iodide', ppt: 'AgI', color: '#facc15', obs: 'precipitate_bright_yellow', name: 'Silver Iodide' },
    { cation: 'AgNO3', catName: 'Silver', anion: 'Na2CrO4', anName: 'Chromate', ppt: 'Ag2CrO4', color: '#b91c1c', obs: 'precipitate_brick_red', name: 'Silver Chromate' },
    { cation: 'BaCl2', catName: 'Barium', anion: 'Na2SO4', anName: 'Sulphate', ppt: 'BaSO4', color: '#ffffff', obs: 'precipitate_dense_white', name: 'Barium Sulphate' },
    { cation: 'BaCl2', catName: 'Barium', anion: 'Na2CO3', anName: 'Carbonate', ppt: 'BaCO3', color: '#ffffff', obs: 'precipitate_white', name: 'Barium Carbonate' },
    { cation: 'BaCl2', catName: 'Barium', anion: 'Na2C2O4', anName: 'Oxalate', ppt: 'BaC2O4', color: '#ffffff', obs: 'precipitate_white', name: 'Barium Oxalate' },
    { cation: 'Pb(NO3)2', catName: 'Lead', anion: 'KI', anName: 'Iodide', ppt: 'PbI2', color: '#facc15', obs: 'precipitate_golden_yellow_spangles', name: 'Lead(II) Iodide (Golden Rain)' },
    { cation: 'Pb(NO3)2', catName: 'Lead', anion: 'Na2CrO4', anName: 'Chromate', ppt: 'PbCrO4', color: '#eab308', obs: 'precipitate_chrome_yellow', name: 'Lead Chromate' },
    { cation: 'Pb(NO3)2', catName: 'Lead', anion: 'Na2SO4', anName: 'Sulphate', ppt: 'PbSO4', color: '#ffffff', obs: 'precipitate_white', name: 'Lead Sulphate' },
    { cation: 'Pb(NO3)2', catName: 'Lead', anion: 'NaCl', anName: 'Chloride', ppt: 'PbCl2', color: '#ffffff', obs: 'precipitate_white_hot_soluble', name: 'Lead Chloride' },
    { cation: 'CuSO4', catName: 'Copper', anion: 'NaOH', anName: 'Hydroxide', ppt: 'Cu(OH)2', color: '#0ea5e9', obs: 'precipitate_pale_blue', name: 'Copper(II) Hydroxide' },
    { cation: 'FeCl3', catName: 'Iron(III)', anion: 'NaOH', anName: 'Hydroxide', ppt: 'Fe(OH)3', color: '#991b1b', obs: 'precipitate_reddish_brown', name: 'Iron(III) Hydroxide' },
    { cation: 'FeSO4', catName: 'Iron(II)', anion: 'NaOH', anName: 'Hydroxide', ppt: 'Fe(OH)2', color: '#059669', obs: 'precipitate_dirty_green', name: 'Iron(II) Hydroxide' },
    { cation: 'ZnSO4', catName: 'Zinc', anion: 'NaOH', anName: 'Hydroxide', ppt: 'Zn(OH)2', color: '#ffffff', obs: 'precipitate_gelatinous_white', name: 'Zinc Hydroxide' },
    { cation: 'NiCl2', catName: 'Nickel', anion: 'NaOH', anName: 'Hydroxide', ppt: 'Ni(OH)2', color: '#10b981', obs: 'precipitate_apple_green', name: 'Nickel Hydroxide' },
    { cation: 'CaCl2', catName: 'Calcium', anion: 'Na2C2O4', anName: 'Oxalate', ppt: 'CaC2O4', color: '#ffffff', obs: 'precipitate_white_insoluble', name: 'Calcium Oxalate' },
    { cation: 'CaCl2', catName: 'Calcium', anion: 'Na2CO3', anName: 'Carbonate', ppt: 'CaCO3', color: '#ffffff', obs: 'precipitate_chalk_white', name: 'Calcium Carbonate' },
    { cation: 'CuSO4', catName: 'Copper', anion: 'K4FeCN6', anName: 'Hexacyanoferrate', ppt: 'Cu2FeCN6', color: '#78350f', obs: 'precipitate_chocolate_brown', name: 'Copper Ferrocyanide (Chocolate Brown)' },
    { cation: 'FeCl3', catName: 'Iron(III)', anion: 'K4FeCN6', anName: 'Hexacyanoferrate', ppt: 'Fe4FeCN6_3', color: '#1e3a8a', obs: 'precipitate_prussian_blue', name: 'Prussian Blue (Fe4[Fe(CN)6]3)' },
  ];

  PRECIP_PAIRS.forEach((p, idx) => {
    generated.push({
      id: `rx_precip_${idx}`,
      name: `Precipitation of ${p.name}`,
      category: 'Precipitation & Salt Matrix',
      inputs: [p.cation, p.anion],
      conditions: ['aqueous', 'mix'],
      products: [p.ppt],
      equation: `${p.cation} + ${p.anion} ──► ${p.ppt}↓ + Byproducts`,
      type: 'Double Displacement Precipitation',
      color: p.color,
      observation: p.obs,
      description: `Double displacement produces insoluble ${p.name} precipitate with distinctive ${p.obs.replace('precipitate_', '').replace(/_/g, ' ')}.`,
      mechanism: 'Ionic pairing exceeding solubility product Ksp.',
      jeeRelevance: 'Essential qualitative inorganic salt analysis test',
      xp: 120,
    });
  });

  // D. Metal Activity Series Displacement Matrix (12 Metals x 12 Salt Solutions = 144 reactions)
  const METALS = [
    { symbol: 'K', name: 'Potassium', react: 12 },
    { symbol: 'Na', name: 'Sodium', react: 11 },
    { symbol: 'Ca', name: 'Calcium', react: 10 },
    { symbol: 'Mg', name: 'Magnesium', react: 9 },
    { symbol: 'Al', name: 'Aluminium', react: 8 },
    { symbol: 'Mn', name: 'Manganese', react: 7 },
    { symbol: 'Zn', name: 'Zinc', react: 6 },
    { symbol: 'Cr', name: 'Chromium', react: 5 },
    { symbol: 'Fe', name: 'Iron', react: 4 },
    { symbol: 'Sn', name: 'Tin', react: 3 },
    { symbol: 'Pb', name: 'Lead', react: 2 },
    { symbol: 'Cu', name: 'Copper', react: 1 },
  ];

  const SALT_SOLUTIONS = [
    { formula: 'CuSO4', cation: 'Cu', name: 'Copper Sulphate', color: '#0ea5e9', outColor: '#f97316' },
    { formula: 'AgNO3', cation: 'Ag', name: 'Silver Nitrate', color: '#f8fafc', outColor: '#cbd5e1' },
    { formula: 'FeSO4', cation: 'Fe', name: 'Iron Sulphate', color: '#10b981', outColor: '#64748b' },
    { formula: 'Pb(NO3)2', cation: 'Pb', name: 'Lead Nitrate', color: '#f8fafc', outColor: '#475569' },
    { formula: 'ZnSO4', cation: 'Zn', name: 'Zinc Sulphate', color: '#e0f2fe', outColor: '#94a3b8' },
    { formula: 'NiSO4', cation: 'Ni', name: 'Nickel Sulphate', color: '#10b981', outColor: '#334155' },
    { formula: 'SnCl2', cation: 'Sn', name: 'Tin(II) Chloride', color: '#f8fafc', outColor: '#64748b' },
    { formula: 'CdSO4', cation: 'Cd', name: 'Cadmium Sulphate', color: '#f8fafc', outColor: '#94a3b8' },
    { formula: 'CoSO4', cation: 'Co', name: 'Cobalt Sulphate', color: '#f43f5e', outColor: '#475569' },
    { formula: 'Bi(NO3)3', cation: 'Bi', name: 'Bismuth Nitrate', color: '#f8fafc', outColor: '#334155' },
    { formula: 'Hg(NO3)2', cation: 'Hg', name: 'Mercury(II) Nitrate', color: '#f8fafc', outColor: '#94a3b8' },
    { formula: 'AuCl3', cation: 'Au', name: 'Gold(III) Chloride', color: '#facc15', outColor: '#eab308' },
  ];

  METALS.forEach((metal) => {
    SALT_SOLUTIONS.forEach((salt) => {
      const saltCationMetal = METALS.find((m) => m.symbol === salt.cation);
      const saltRank = saltCationMetal ? saltCationMetal.react : 0;
      if (metal.react > saltRank) {
        generated.push({
          id: `rx_disp_${metal.symbol}_${salt.formula}`,
          name: `Single Displacement: ${metal.name} + ${salt.name}`,
          category: 'Precipitation & Salt Matrix',
          inputs: [metal.symbol, salt.formula],
          conditions: ['aqueous'],
          products: [salt.cation, `${metal.symbol}Salt`],
          equation: `${metal.symbol}(s) + ${salt.formula}(aq) ──► ${salt.cation}↓(s) + ${metal.symbol}-salt(aq)`,
          type: 'Single Displacement Redox',
          color: salt.outColor,
          observation: 'metal_deposits_color_fades',
          description: `More electropositive ${metal.name} displaces ${salt.cation} from ${salt.name}; elemental ${salt.cation} deposits on metal surface.`,
          mechanism: 'Electrochemical potential difference drives electron transfer.',
          jeeRelevance: 'Standard reactivity series verification',
          xp: 110,
        });
      }
    });
  });

  // E. Esterification Fragrance Matrix (15 Carboxylic Acids x 12 Alcohols = 180 reactions)
  const ESTER_ACIDS = [
    { formula: 'CH3COOH', name: 'Acetic Acid' },
    { formula: 'HCOOH', name: 'Formic Acid' },
    { formula: 'C2H5COOH', name: 'Propionic Acid' },
    { formula: 'C3H7COOH', name: 'Butyric Acid' },
    { formula: 'C6H5COOH', name: 'Benzoic Acid' },
    { formula: 'C4H9COOH', name: 'Valeric Acid' },
    { formula: 'C7H15COOH', name: 'Octanoic Acid' },
    { formula: 'C5H11COOH', name: 'Hexanoic Acid' },
    { formula: 'C8H17COOH', name: 'Nonanoic Acid' },
    { formula: 'C9H19COOH', name: 'Decanoic Acid' },
    { formula: 'C6H4(OH)COOH', name: 'Salicylic Acid' },
    { formula: 'CH2=CHCOOH', name: 'Acrylic Acid' },
    { formula: 'CH3CH=CHCOOH', name: 'Crotonic Acid' },
    { formula: 'C6H5CH2COOH', name: 'Phenylacetic Acid' },
    { formula: 'C6H5CH=CHCOOH', name: 'Cinnamic Acid' },
  ];

  const ESTER_ALCOHOLS = [
    { formula: 'CH3OH', name: 'Methanol', scent: 'wintergreen / fresh fruit' },
    { formula: 'C2H5OH', name: 'Ethanol', scent: 'sweet pear / apple' },
    { formula: 'C3H7OH', name: 'Propanol', scent: 'ripe banana / tropical' },
    { formula: 'C4H9OH', name: 'Butanol', scent: 'fruity pineapple' },
    { formula: 'C5H11OH', name: 'Pentanol (Isoamyl Alcohol)', scent: 'intense banana essence' },
    { formula: 'C6H13OH', name: 'Hexanol', scent: 'fresh grassy herbal' },
    { formula: 'C7H15OH', name: 'Heptanol', scent: 'sweet green floral' },
    { formula: 'C8H17OH', name: 'Octanol', scent: 'sweet orange peel' },
    { formula: 'C10H21OH', name: 'Decanol', scent: 'citrus orange flower' },
    { formula: 'C6H5CH2OH', name: 'Benzyl Alcohol', scent: 'jasmine floral' },
    { formula: 'C6H5CH2CH2OH', name: 'Phenylethyl Alcohol', scent: 'deep damask rose' },
    { formula: 'CH(CH3)2OH', name: 'Isopropanol', scent: 'fruity solvent' },
  ];

  ESTER_ACIDS.forEach((acid, aIdx) => {
    ESTER_ALCOHOLS.forEach((alc, alIdx) => {
      generated.push({
        id: `rx_ester_${aIdx}_${alIdx}`,
        name: `Fischer Esterification: ${acid.name} + ${alc.name}`,
        category: 'Esterification & Scents',
        inputs: [acid.formula, alc.formula, 'H2SO4'],
        conditions: ['heat_water_bath'],
        products: ['Ester', 'H2O'],
        equation: `${acid.formula} + ${alc.formula} ──(conc. H₂SO₄, Δ)──► Sweet Ester (${alc.scent}) + H₂O`,
        type: 'Fischer Esterification',
        color: '#fef08a',
        observation: 'fruity_ester_scent',
        description: `Acid-catalyzed condensation between ${acid.name} and ${alc.name} yielding fragrant ester with pleasant note of ${alc.scent}.`,
        mechanism: 'Protonation of carboxylic carbonyl followed by alcohol nucleophilic addition and loss of water.',
        jeeRelevance: 'Common functional test for alcohols and carboxylic acids',
        xp: 160,
      });
    });
  });

  // F. Carbonate / Bicarbonate Acid Decomposition Matrix (15 Carbonates x 12 Acids = 180 reactions)
  const CARBONATES = [
    { formula: 'CaCO3', name: 'Calcium Carbonate' },
    { formula: 'Na2CO3', name: 'Sodium Carbonate' },
    { formula: 'NaHCO3', name: 'Sodium Bicarbonate' },
    { formula: 'K2CO3', name: 'Potassium Carbonate' },
    { formula: 'KHCO3', name: 'Potassium Bicarbonate' },
    { formula: 'MgCO3', name: 'Magnesium Carbonate' },
    { formula: 'BaCO3', name: 'Barium Carbonate' },
    { formula: 'SrCO3', name: 'Strontium Carbonate' },
    { formula: 'ZnCO3', name: 'Zinc Carbonate' },
    { formula: 'CuCO3', name: 'Copper Carbonate' },
    { formula: 'PbCO3', name: 'Lead Carbonate' },
    { formula: 'FeCO3', name: 'Iron(II) Carbonate (Siderite)' },
    { formula: 'MnCO3', name: 'Manganese Carbonate' },
    { formula: 'NiCO3', name: 'Nickel Carbonate' },
    { formula: 'Li2CO3', name: 'Lithium Carbonate' },
  ];

  const DECOMP_ACIDS = [
    { formula: 'HCl', name: 'Hydrochloric Acid' },
    { formula: 'HNO3', name: 'Nitric Acid' },
    { formula: 'H2SO4', name: 'Sulphuric Acid' },
    { formula: 'CH3COOH', name: 'Acetic Acid' },
    { formula: 'HCOOH', name: 'Formic Acid' },
    { formula: 'HBr', name: 'Hydrobromic Acid' },
    { formula: 'HI', name: 'Hydroiodic Acid' },
    { formula: 'H3PO4', name: 'Phosphoric Acid' },
    { formula: 'C6H5COOH', name: 'Benzoic Acid' },
    { formula: 'C2H5COOH', name: 'Propionic Acid' },
    { formula: 'HClO4', name: 'Perchloric Acid' },
    { formula: 'H2C2O4', name: 'Oxalic Acid' },
  ];

  CARBONATES.forEach((carb, cIdx) => {
    DECOMP_ACIDS.forEach((acid, aIdx) => {
      generated.push({
        id: `rx_carb_eff_${cIdx}_${aIdx}`,
        name: `Effervescence: ${carb.name} + ${acid.name}`,
        category: 'Acids & Bases (Neutralization)',
        inputs: [carb.formula, acid.formula],
        conditions: ['room_temp'],
        products: ['CO2', 'H2O', 'Salt'],
        equation: `${carb.formula} + ${acid.formula} ──► CO₂↑ (Brisk Effervescence) + H₂O + Salt`,
        type: 'Carbonate Acid Decomposition',
        color: '#f8fafc',
        observation: 'vigorous_co2_effervescence',
        description: `Rapid evolution of carbon dioxide gas bubbles turning lime water milky when ${carb.name} reacts with ${acid.name}.`,
        mechanism: 'Unstable carbonic acid intermediate decomposes to water and CO2 gas.',
        jeeRelevance: 'Universal confirmatory test for carbonate and bicarbonate anions',
        xp: 100,
      });
    });
  });

  return [...CURATED_MASTER_REACTIONS, ...generated];
}

function formatSalt(cation, cVal, anion, aVal) {
  if (cVal === aVal) return `${cation}${anion}`;
  if (cVal === 1 && aVal === 2) return `${cation}2${anion}`;
  if (cVal === 1 && aVal === 3) return `${cation}3${anion}`;
  if (cVal === 2 && aVal === 1) return `${cation}(${anion})2`;
  if (cVal === 2 && aVal === 3) return `${cation}3(${anion})2`;
  if (cVal === 3 && aVal === 1) return `${cation}(${anion})3`;
  if (cVal === 3 && aVal === 2) return `${cation}2(${anion})3`;
  return `${cation}${anion}`;
}

// Global cached instance
export const ALL_REACTIONS = generateAllReactions();

export function getReactionCount() {
  return ALL_REACTIONS.length;
}

// Fast Reaction Matcher: Given an array of reactant formulas and optional conditions,
// finds the best matching reaction from the >2,000 reaction database.
export function matchReactionLocally(inputFormulas = [], conditions = []) {
  if (!inputFormulas || inputFormulas.length === 0) return null;

  const normalize = (s) => (s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  const inputSet = new Set(inputFormulas.map(normalize).filter(Boolean));
  const condSet = new Set(conditions.map(normalize).filter(Boolean));

  // Find reactions where all required inputs are present in the vessel
  const candidates = ALL_REACTIONS.filter((rx) => {
    const rxInputs = rx.inputs.map(normalize).filter(Boolean);
    if (rxInputs.length === 0) return false;
    return rxInputs.every((req) => inputSet.has(req));
  });

  if (candidates.length === 0) return null;

  // Exact condition match preferred
  const withConds = candidates.find((rx) => {
    if (!rx.conditions || rx.conditions.length === 0) return true;
    return rx.conditions.map(normalize).every((c) => condSet.has(c));
  });

  return withConds || candidates[0];
}
